import type { CurriculumTopic } from "./types";

export const A1_TOPICS: CurriculumTopic[] = [
  {
    order: 1,
    level: "A1",
    title: "Uzbek Alphabet & Latin Sounds",
    titleUzbek: "O'zbek alifbosi va tovushlar",
    category: "Foundations",
    description: "Learn the 29 letters of modern Uzbek Latin alphabet, focusing on special letters like O', G', Sh, and Ch.",
    keyVocabulary: [
      { uzbek: "harf", english: "letter" },
      { uzbek: "tovush", english: "sound" },
      { uzbek: "so'z", english: "word" },
      { uzbek: "alifbo", english: "alphabet" },
    ],
    grammarFocus: "Uzbek uses Latin script since 1993 with distinct apostrophe letters: O' and G'.",
  },
  {
    order: 2,
    level: "A1",
    title: "Informal Greetings",
    titleUzbek: "Oddiy salomlashish",
    category: "Foundations",
    description: "Master casual greetings used with friends, peers, and family members.",
    keyVocabulary: [
      { uzbek: "Salom", english: "Hello / Hi" },
      { uzbek: "Qalesiz?", english: "How are you? (friendly)" },
      { uzbek: "Yaxshimisiz?", english: "Are you well?" },
      { uzbek: "Tuzukmisiz?", english: "Are you feeling okay?" },
    ],
    grammarFocus: "Informal greetings often use the question clitic -mi ('Yaxshimisiz?').",
  },
  {
    order: 3,
    level: "A1",
    title: "Formal Greetings & Respect",
    titleUzbek: "Rasmiy salomlashish va ehtirom",
    category: "Foundations",
    description: "Learn the traditional Islamic-Uzbek greeting and respectful forms for elders.",
    keyVocabulary: [
      { uzbek: "Assalomu alaykum", english: "Peace be upon you (Formal Hello)" },
      { uzbek: "Vaalaykum assalom", english: "And upon you be peace (Response)" },
      { uzbek: "Xush kelibsiz", english: "Welcome" },
      { uzbek: "Ahvollaringiz qanday?", english: "How are your affairs?" },
    ],
    grammarFocus: "Plural suffix -lar is used with elders as an honorific marker of respect.",
  },
  {
    order: 4,
    level: "A1",
    title: "Saying Goodbye",
    titleUzbek: "Xayrlashuv so'zlari",
    category: "Foundations",
    description: "Expressing farewell in both casual and polite situations.",
    keyVocabulary: [
      { uzbek: "Xayr", english: "Goodbye" },
      { uzbek: "Ko'rishguncha", english: "See you later / Until we meet" },
      { uzbek: "Yaxshi qoling", english: "Stay well (said to the person staying)" },
      { uzbek: "Yaxshi boring", english: "Go well (said to the person leaving)" },
    ],
    grammarFocus: "Distinguish between 'Yaxshi qoling' (to stayer) and 'Yaxshi boring' (to leaver).",
  },
  {
    order: 5,
    level: "A1",
    title: "Polite Words & Courtesy",
    titleUzbek: "Xushmuomalalik so'zlari",
    category: "Foundations",
    description: "Essential courtesy phrases for expressing gratitude and asking for pardon.",
    keyVocabulary: [
      { uzbek: "Rahmat", english: "Thank you" },
      { uzbek: "Katta rahmat", english: "Thank you very much" },
      { uzbek: "Iltimos", english: "Please" },
      { uzbek: "Kechirasiz", english: "Excuse me / Sorry" },
      { uzbek: "Arzimaydi", english: "You're welcome / Not at all" },
    ],
    grammarFocus: "Polite imperative suffix -ingiz softens commands into courteous requests.",
  },
  {
    order: 6,
    level: "A1",
    title: "Asking and Telling Names",
    titleUzbek: "Ismni so'rash va aytish",
    category: "Foundations",
    description: "How to introduce yourself and ask other people's names.",
    keyVocabulary: [
      { uzbek: "Ismingiz nima?", english: "What is your name? (polite)" },
      { uzbek: "Mening ismim...", english: "My name is..." },
      { uzbek: "Tanishganimdan xursandman", english: "Pleased to meet you" },
      { uzbek: "ism", english: "name" },
    ],
    grammarFocus: "Possessive suffix -im denotes 'my' ('ismim' = my name) and -ingiz denotes 'your'.",
  },
  {
    order: 7,
    level: "A1",
    title: "Personal Pronouns",
    titleUzbek: "Kishilik olmoshlari",
    category: "Grammar Essentials",
    description: "Master the 6 personal pronouns in Uzbek: men, sen, u, biz, siz, ular.",
    keyVocabulary: [
      { uzbek: "men", english: "I" },
      { uzbek: "sen", english: "you (informal)" },
      { uzbek: "u", english: "he / she / it" },
      { uzbek: "biz", english: "we" },
      { uzbek: "siz", english: "you (formal/polite)" },
      { uzbek: "ular", english: "they" },
    ],
    grammarFocus: "Uzbek has no gendered pronouns: 'u' means he, she, and it.",
  },
  {
    order: 8,
    level: "A1",
    title: "Predicative Suffixes (Verb 'To Be')",
    titleUzbek: "Kesimlik qo'shimchalari",
    category: "Grammar Essentials",
    description: "Learn how Uzbek expresses 'to be' using personal suffixes attached to nouns.",
    keyVocabulary: [
      { uzbek: "Men talabaman", english: "I am a student" },
      { uzbek: "Siz o'qituvchisiz", english: "You are a teacher" },
      { uzbek: "Biz do'stmiz", english: "We are friends" },
      { uzbek: "talaba", english: "student" },
    ],
    grammarFocus: "Affirmative predicative suffixes: -man (1st sg), -san (2nd sg), -miz (1st pl), -siz (2nd pl).",
  },
  {
    order: 9,
    level: "A1",
    title: "Negation with Emas",
    titleUzbek: "Emas so'zi bilan inkor",
    category: "Grammar Essentials",
    description: "Use 'emas' to say 'is not / am not / are not' in Uzbek.",
    keyVocabulary: [
      { uzbek: "emas", english: "is not" },
      { uzbek: "Men talaba emasman", english: "I am not a student" },
      { uzbek: "Bu qiyin emas", english: "This is not difficult" },
      { uzbek: "qiyin", english: "difficult" },
    ],
    grammarFocus: "Personal suffixes attach to 'emas': emasman, emassan, emasmiz, emassiz.",
  },
  {
    order: 10,
    level: "A1",
    title: "Numbers 0 to 10",
    titleUzbek: "0 dan 10 gacha sonlar",
    category: "Foundations",
    description: "Counting and identifying basic single-digit numbers.",
    keyVocabulary: [
      { uzbek: "nol", english: "zero" },
      { uzbek: "bir, ikki, uch", english: "one, two, three" },
      { uzbek: "to'rt, besh, olti", english: "four, five, six" },
      { uzbek: "yetti, sakkiz, to'qqiz, o'n", english: "seven, eight, nine, ten" },
    ],
    grammarFocus: "Nouns following numerals in Uzbek always remain in the singular form (e.g. besh kitob, NOT besh kitoblar).",
  },
  {
    order: 11,
    level: "A1",
    title: "Numbers 11 to 20",
    titleUzbek: "11 dan 20 gacha sonlar",
    category: "Foundations",
    description: "Combining 'o'n' with single digits to form numbers 11 through 20.",
    keyVocabulary: [
      { uzbek: "o'n bir", english: "eleven" },
      { uzbek: "o'n ikki", english: "twelve" },
      { uzbek: "o'n besh", english: "fifteen" },
      { uzbek: "yigirma", english: "twenty" },
    ],
    grammarFocus: "Teen numbers simply combine 'o'n' + unit (e.g., o'n uch = 13, o'n to'rt = 14).",
  },
  {
    order: 12,
    level: "A1",
    title: "Tens and Numbers up to 100",
    titleUzbek: "O'nliklar va 100 gacha sonlar",
    category: "Foundations",
    description: "Counting by tens from 10 to 100.",
    keyVocabulary: [
      { uzbek: "o'ttiz", english: "thirty" },
      { uzbek: "qirq", english: "forty" },
      { uzbek: "ellik", english: "fifty" },
      { uzbek: "oltmish, yetmish", english: "sixty, seventy" },
      { uzbek: "sakson, to'qson, yuz", english: "eighty, ninety, hundred" },
    ],
    grammarFocus: "Compound numbers are formed regularly: ellik besh (55), yetmish ikki (72).",
  },
  {
    order: 13,
    level: "A1",
    title: "Demonstrative Pronouns",
    titleUzbek: "Ko'rsatish olmoshlari",
    category: "Grammar Essentials",
    description: "Pointing out objects near, intermediate, and far using bu, shu, u, and o'sha.",
    keyVocabulary: [
      { uzbek: "bu", english: "this (near speaker)" },
      { uzbek: "shu", english: "this / that (just mentioned)" },
      { uzbek: "u", english: "that (far)" },
      { uzbek: "o'sha", english: "that very / that one over there" },
    ],
    grammarFocus: "'Bu' indicates immediate proximity; 'u' and 'o'sha' indicate distance.",
  },
  {
    order: 14,
    level: "A1",
    title: "Asking 'What is this?'",
    titleUzbek: "'Bu nima?' deb so'rash",
    category: "Foundations",
    description: "Inquiring about inanimate objects using 'nima'.",
    keyVocabulary: [
      { uzbek: "Bu nima?", english: "What is this?" },
      { uzbek: "Bu kitob", english: "This is a book" },
      { uzbek: "nima", english: "what" },
      { uzbek: "daftar", english: "notebook" },
    ],
    grammarFocus: "Questions with interrogative words like 'nima' do not take the question particle -mi.",
  },
  {
    order: 15,
    level: "A1",
    title: "Asking 'Who is this?'",
    titleUzbek: "'Bu kim?' deb so'rash",
    category: "Foundations",
    description: "Inquiring about people and identities using 'kim'.",
    keyVocabulary: [
      { uzbek: "Bu kim?", english: "Who is this?" },
      { uzbek: "Bu mening do'stim", english: "This is my friend" },
      { uzbek: "kim", english: "who" },
      { uzbek: "do'st", english: "friend" },
    ],
    grammarFocus: "Use 'kim' for all persons regardless of gender or social status.",
  },
  {
    order: 16,
    level: "A1",
    title: "Yes/No Questions with -mi",
    titleUzbek: "-mi so'roq yuklamasi",
    category: "Grammar Essentials",
    description: "Forming questions in Uzbek by appending the clitic -mi to words.",
    keyVocabulary: [
      { uzbek: "Bu qalammi?", english: "Is this a pencil?" },
      { uzbek: "Ha, bu qalam", english: "Yes, this is a pencil" },
      { uzbek: "Yo'q, bu ruchka", english: "No, this is a pen" },
      { uzbek: "ha / yo'q", english: "yes / no" },
    ],
    grammarFocus: "The clitic -mi attaches to the word being questioned and is never stressed.",
  },
  {
    order: 17,
    level: "A1",
    title: "Existence with Bor and Yo'q",
    titleUzbek: "Bor va Yo'q (Mavjudlik)",
    category: "Grammar Essentials",
    description: "Saying 'there is' (bor) and 'there is not / none' (yo'q).",
    keyVocabulary: [
      { uzbek: "bor", english: "there is / exists / available" },
      { uzbek: "yo'q", english: "there is not / none / absent" },
      { uzbek: "Choy bormi?", english: "Is there tea?" },
      { uzbek: "Vaqt yo'q", english: "There is no time" },
    ],
    grammarFocus: "'Bor' and 'yo'q' also express possession when paired with possessive nouns ('Mening kitobim bor').",
  },
  {
    order: 18,
    level: "A1",
    title: "Plural Suffix -lar",
    titleUzbek: "-lar ko'plik qo'shimchasi",
    category: "Grammar Essentials",
    description: "Making nouns plural by adding the universal suffix -lar.",
    keyVocabulary: [
      { uzbek: "kitoblar", english: "books" },
      { uzbek: "uylar", english: "houses" },
      { uzbek: "shahar", english: "city" },
      { uzbek: "shaharlar", english: "cities" },
    ],
    grammarFocus: "The plural suffix -lar does not undergo vowel harmony and is identical for all nouns.",
  },
  {
    order: 19,
    level: "A1",
    title: "Basic Descriptive Adjectives",
    titleUzbek: "Oddiy sifatlar",
    category: "Vocabulary",
    description: "Core descriptive adjectives for size, quality, and condition.",
    keyVocabulary: [
      { uzbek: "katta", english: "big / large" },
      { uzbek: "kichik", english: "small / little" },
      { uzbek: "yaxshi", english: "good / fine" },
      { uzbek: "yomon", english: "bad" },
      { uzbek: "yangi", english: "new" },
      { uzbek: "eski", english: "old (for objects)" },
    ],
    grammarFocus: "Adjectives precede the noun they modify and do not agree in number (e.g. katta uylar).",
  },
  {
    order: 20,
    level: "A1",
    title: "Colors in Uzbek",
    titleUzbek: "Ranglar",
    category: "Vocabulary",
    description: "Naming primary and common colors.",
    keyVocabulary: [
      { uzbek: "oq", english: "white" },
      { uzbek: "qora", english: "black" },
      { uzbek: "qizil", english: "red" },
      { uzbek: "ko'k", english: "blue / green (folklore)" },
      { uzbek: "yashil", english: "green" },
      { uzbek: "sariq", english: "yellow" },
    ],
    grammarFocus: "'Ko'k' primarily means blue in modern Uzbek, while 'yashil' specifically denotes green.",
  },
  {
    order: 21,
    level: "A1",
    title: "Days of the Week",
    titleUzbek: "Hafta kunlari",
    category: "Everyday Life",
    description: "Learning the Persian-influenced names of all seven days of the week.",
    keyVocabulary: [
      { uzbek: "dushanba", english: "Monday" },
      { uzbek: "seshanba", english: "Tuesday" },
      { uzbek: "chorshanba", english: "Wednesday" },
      { uzbek: "payshanba", english: "Thursday" },
      { uzbek: "juma", english: "Friday" },
      { uzbek: "shanba / yakshanba", english: "Saturday / Sunday" },
    ],
    grammarFocus: "To say 'on Monday', use locative suffix -da: 'Dushanba kuni' or 'Dushanbada'.",
  },
  {
    order: 22,
    level: "A1",
    title: "Months of the Year",
    titleUzbek: "Yil oylari",
    category: "Everyday Life",
    description: "Mastering the names of the 12 calendar months.",
    keyVocabulary: [
      { uzbek: "yanvar, fevral, mart", english: "January, February, March" },
      { uzbek: "aprel, may, iyun", english: "April, May, June" },
      { uzbek: "iyul, avgust, sentabr", english: "July, August, September" },
      { uzbek: "oktabr, noyabr, dekabr", english: "October, November, December" },
    ],
    grammarFocus: "Months are capitalized or lowercased based on context, followed by 'oyida' for 'in the month of'.",
  },
  {
    order: 23,
    level: "A1",
    title: "The Four Seasons",
    titleUzbek: "To'rt fasl",
    category: "Everyday Life",
    description: "Describing spring, summer, autumn, and winter in Uzbekistan.",
    keyVocabulary: [
      { uzbek: "bahor", english: "spring" },
      { uzbek: "yoz", english: "summer" },
      { uzbek: "kuz", english: "autumn / fall" },
      { uzbek: "qish", english: "winter" },
      { uzbek: "fasl", english: "season" },
    ],
    grammarFocus: "Attach -da for temporal expressions: 'yozda' (in summer), 'bahorda' (in spring).",
  },
  {
    order: 24,
    level: "A1",
    title: "Asking the Time",
    titleUzbek: "Soat necha?",
    category: "Everyday Life",
    description: "Inquiring about current time and telling exact hours.",
    keyVocabulary: [
      { uzbek: "Soat necha?", english: "What time is it?" },
      { uzbek: "Soat uch", english: "It is three o'clock" },
      { uzbek: "Soat nechada?", english: "At what time?" },
      { uzbek: "vaqt", english: "time" },
    ],
    grammarFocus: "'Soat necha?' asks current time; 'Soat nechada?' asks at what time an action occurs.",
  },
  {
    order: 25,
    level: "A1",
    title: "Telling Half Hours & Minutes",
    titleUzbek: "Yarim va daqiqalar",
    category: "Everyday Life",
    description: "Using 'yarim' (half) and minutes past/to the hour.",
    keyVocabulary: [
      { uzbek: "yarim", english: "half" },
      { uzbek: "Soat ikki yarim", english: "It is 2:30" },
      { uzbek: "daqiqa / minut", english: "minute" },
      { uzbek: "o'tdi", english: "past (minutes)" },
      { uzbek: "qoldi", english: "to (minutes until)" },
    ],
    grammarFocus: "Format: 'Soat uchdan o'n daqiqa o'tdi' (10 past 3) uses ablative -dan + o'tdi.",
  },
  {
    order: 26,
    level: "A1",
    title: "Immediate Family Members",
    titleUzbek: "Yaqin oila a'zolari",
    category: "Everyday Life",
    description: "Talking about parents, brothers, and sisters.",
    keyVocabulary: [
      { uzbek: "ota / dada", english: "father / dad" },
      { uzbek: "ona / oyi", english: "mother / mom" },
      { uzbek: "aka", english: "older brother" },
      { uzbek: "uka", english: "younger brother" },
      { uzbek: "opa", english: "older sister" },
      { uzbek: "singil", english: "younger sister" },
    ],
    grammarFocus: "Uzbek distinguishes between older (aka/opa) and younger (uka/singil) siblings.",
  },
  {
    order: 27,
    level: "A1",
    title: "Extended Family Members",
    titleUzbek: "Katta oila va qarindoshlar",
    category: "Everyday Life",
    description: "Words for grandparents, uncles, and aunts.",
    keyVocabulary: [
      { uzbek: "bobo", english: "grandfather" },
      { uzbek: "buvi", english: "grandmother" },
      { uzbek: "amaki", english: "paternal uncle" },
      { uzbek: "tog'a", english: "maternal uncle" },
      { uzbek: "xola", english: "maternal aunt" },
      { uzbek: "amma", english: "paternal aunt" },
    ],
    grammarFocus: "Uzbek differentiates paternal (amaki/amma) from maternal (tog'a/xola) relatives.",
  },
  {
    order: 28,
    level: "A1",
    title: "Possessive Suffixes: Singular",
    titleUzbek: "Birlik egalik qo'shimchalari",
    category: "Grammar Essentials",
    description: "Attaching possessive endings for my, your, and his/her/its.",
    keyVocabulary: [
      { uzbek: "kitobim", english: "my book (-im)" },
      { uzbek: "kitobing", english: "your book (-ing)" },
      { uzbek: "kitobi", english: "his/her book (-i)" },
      { uzbek: "onasi", english: "his/her mother (-si after vowel)" },
    ],
    grammarFocus: "Consonant stems take -im/-ing/-i; vowel stems take -m/-ng/-si.",
  },
  {
    order: 29,
    level: "A1",
    title: "Possessive Suffixes: Plural",
    titleUzbek: "Ko'plik egalik qo'shimchalari",
    category: "Grammar Essentials",
    description: "Attaching possessive endings for our, your (formal/plural), and their.",
    keyVocabulary: [
      { uzbek: "uyimiz", english: "our house (-imiz)" },
      { uzbek: "uyingiz", english: "your house (polite/pl) (-ingiz)" },
      { uzbek: "uylari", english: "their house / his house (polite) (-lari)" },
      { uzbek: "oila", english: "family" },
    ],
    grammarFocus: "-ingiz is the default polite form used when speaking to a single adult.",
  },
  {
    order: 30,
    level: "A1",
    title: "Genitive Case (-ning)",
    titleUzbek: "Qaratqich kelishigi (-ning)",
    category: "Grammar Essentials",
    description: "Expressing possession of nouns: 'X-ning Y-si' (X's Y).",
    keyVocabulary: [
      { uzbek: "Ali-ning kitobi", english: "Ali's book" },
      { uzbek: "Mening do'stim", english: "My friend" },
      { uzbek: "shahar-ning markazi", english: "center of the city" },
      { uzbek: "markaz", english: "center" },
    ],
    grammarFocus: "The owner takes -ning and the possessed item takes the possessive suffix (-i/-si).",
  },
  {
    order: 31,
    level: "A1",
    title: "Asking and Stating Age",
    titleUzbek: "Yoshni so'rash va aytish",
    category: "Everyday Life",
    description: "How to state how old you are and ask someone's age.",
    keyVocabulary: [
      { uzbek: "Yoshingiz nechida?", english: "How old are you? (polite)" },
      { uzbek: "Men yigirma besh yoshdaman", english: "I am 25 years old" },
      { uzbek: "yosh", english: "age / year of age" },
      { uzbek: "tug'ilgan kun", english: "birthday" },
    ],
    grammarFocus: "Notice the locative suffix: 'yosh-da-man' literally means 'I am at age X'.",
  },
  {
    order: 32,
    level: "A1",
    title: "Countries and Nationalities",
    titleUzbek: "Mamlakatlar va millatlar",
    category: "Culture & Places",
    description: "Talking about origins with -lik suffix.",
    keyVocabulary: [
      { uzbek: "O'zbekiston", english: "Uzbekistan" },
      { uzbek: "o'zbek", english: "Uzbek (person/nationality)" },
      { uzbek: "Amerika", english: "America" },
      { uzbek: "amerikalik", english: "American" },
      { uzbek: "Angliya", english: "England" },
      { uzbek: "angliyalik", english: "English person" },
    ],
    grammarFocus: "The suffix -lik derives nationality or person from a place (Toshkentlik = person from Tashkent).",
  },
  {
    order: 33,
    level: "A1",
    title: "Languages and the Suffix -cha",
    titleUzbek: "Tillar va -cha qo'shimchasi",
    category: "Culture & Places",
    description: "Naming languages with the suffix -cha.",
    keyVocabulary: [
      { uzbek: "o'zbekcha", english: "Uzbek language" },
      { uzbek: "inglizcha", english: "English language" },
      { uzbek: "ruscha", english: "Russian language" },
      { uzbek: "Men o'zbekcha gapiraman", english: "I speak Uzbek" },
    ],
    grammarFocus: "Suffix -cha denotes 'in the manner/language of' (o'zbek + cha = in Uzbek).",
  },
  {
    order: 34,
    level: "A1",
    title: "Common Professions",
    titleUzbek: "Asosiy kasblar",
    category: "Vocabulary",
    description: "Learning names for everyday jobs and careers.",
    keyVocabulary: [
      { uzbek: "o'qituvchi", english: "teacher" },
      { uzbek: "shifokor / do'xtir", english: "doctor" },
      { uzbek: "muhandis", english: "engineer" },
      { uzbek: "haydovchi", english: "driver" },
      { uzbek: "sotuvchi", english: "salesperson" },
    ],
    grammarFocus: "The suffix -chi creates agent nouns of profession (hayda-moq -> haydovchi; sot-moq -> sotuvchi).",
  },
  {
    order: 35,
    level: "A1",
    title: "In the Classroom",
    titleUzbek: "Sinf xonasida",
    category: "Vocabulary",
    description: "Objects and actions in a learning environment.",
    keyVocabulary: [
      { uzbek: "kitob", english: "book" },
      { uzbek: "daftar", english: "notebook" },
      { uzbek: "qalam", english: "pencil" },
      { uzbek: "doska", english: "board / blackboard" },
      { uzbek: "dars", english: "lesson" },
    ],
    grammarFocus: "Compound 'dars qilmoq' means 'to do homework / study'.",
  },
  {
    order: 36,
    level: "A1",
    title: "Everyday Objects",
    titleUzbek: "Kundalik buyumlar",
    category: "Vocabulary",
    description: "Names of personal belongings carried daily.",
    keyVocabulary: [
      { uzbek: "telefon", english: "phone" },
      { uzbek: "kalit", english: "key" },
      { uzbek: "sumka", english: "bag" },
      { uzbek: "hamyon", english: "wallet" },
      { uzbek: "soat", english: "watch / clock" },
    ],
    grammarFocus: "Nouns take possessive endings directly: kalitim (my key), sumkangiz (your bag).",
  },
  {
    order: 37,
    level: "A1",
    title: "Rooms in a House",
    titleUzbek: "Uy xonalari",
    category: "Everyday Life",
    description: "Names of rooms in an Uzbek house or apartment.",
    keyVocabulary: [
      { uzbek: "oshxona", english: "kitchen" },
      { uzbek: "mehmonxona", english: "living room / guest room" },
      { uzbek: "yotoqxona", english: "bedroom" },
      { uzbek: "hammom", english: "bathroom" },
      { uzbek: "xona", english: "room" },
    ],
    grammarFocus: "The Persian suffix -xona designates a place of function (osh + xona = food room).",
  },
  {
    order: 38,
    level: "A1",
    title: "Basic Furniture",
    titleUzbek: "Uy jihozlari",
    category: "Everyday Life",
    description: "Furniture terms for home and work.",
    keyVocabulary: [
      { uzbek: "stol", english: "table / desk" },
      { uzbek: "stul", english: "chair" },
      { uzbek: "karavot", english: "bed" },
      { uzbek: "javon", english: "cupboard / wardrobe" },
      { uzbek: "gilam", english: "carpet / rug" },
    ],
    grammarFocus: "Gilam (carpet) is a central cultural element in traditional Uzbek homes.",
  },
  {
    order: 39,
    level: "A1",
    title: "Parts of the Body",
    titleUzbek: "Tana a'zolari",
    category: "Vocabulary",
    description: "Basic human body parts vocabulary.",
    keyVocabulary: [
      { uzbek: "bosh", english: "head" },
      { uzbek: "ko'z", english: "eye" },
      { uzbek: "quloq", english: "ear" },
      { uzbek: "qo'l", english: "hand / arm" },
      { uzbek: "oyoq", english: "foot / leg" },
    ],
    grammarFocus: "In Uzbek, 'qo'l' covers both hand and arm; 'oyoq' covers both foot and leg.",
  },
  {
    order: 40,
    level: "A1",
    title: "Everyday Clothing",
    titleUzbek: "Kundalik kiyimlar",
    category: "Everyday Life",
    description: "Common clothes worn every day.",
    keyVocabulary: [
      { uzbek: "ko'ylak", english: "shirt / dress" },
      { uzbek: "shim", english: "pants / trousers" },
      { uzbek: "poyabzal / oyoq kiyim", english: "shoes" },
      { uzbek: "kurtka", english: "jacket" },
      { uzbek: "shapka", english: "hat" },
    ],
    grammarFocus: "The verb 'kiymoq' means 'to wear / put on clothes'.",
  },
  {
    order: 41,
    level: "A1",
    title: "Traditional Uzbek Clothing",
    titleUzbek: "Milliy kiyimlar",
    category: "Culture & Places",
    description: "Cultural garments of Uzbekistan.",
    keyVocabulary: [
      { uzbek: "do'ppi", english: "skullcap (traditional cap)" },
      { uzbek: "chopon", english: "quilted robe" },
      { uzbek: "atlas", english: "traditional ikat silk" },
      { uzbek: "belbog'", english: "waist sash" },
    ],
    grammarFocus: "Do'ppi is worn with immense pride at gatherings, ceremonies, and celebrations.",
  },
  {
    order: 42,
    level: "A1",
    title: "Basic Grocery Foods",
    titleUzbek: "Asosiy oziq-ovqat mahsulotlari",
    category: "Food & Dining",
    description: "Staple pantry foods in Uzbek homes.",
    keyVocabulary: [
      { uzbek: "non", english: "bread" },
      { uzbek: "sut", english: "milk" },
      { uzbek: "go'sht", english: "meat" },
      { uzbek: "tuxum", english: "egg" },
      { uzbek: "guruch", english: "rice" },
      { uzbek: "yog'", english: "oil / butter" },
    ],
    grammarFocus: "Bread (non) is sacred in Uzbek culture and must never be placed upside down.",
  },
  {
    order: 43,
    level: "A1",
    title: "Fresh Fruits",
    titleUzbek: "Meva va poliz ekinlari",
    category: "Food & Dining",
    description: "Famous sweet fruits of Uzbekistan.",
    keyVocabulary: [
      { uzbek: "olma", english: "apple" },
      { uzbek: "o'rik", english: "apricot" },
      { uzbek: "anor", english: "pomegranate" },
      { uzbek: "uzum", english: "grapes" },
      { uzbek: "qovun", english: "melon" },
      { uzbek: "tarvuz", english: "watermelon" },
    ],
    grammarFocus: "Uzbek melons and pomegranates are world-renowned for their fragrance and sweetness.",
  },
  {
    order: 44,
    level: "A1",
    title: "Fresh Vegetables",
    titleUzbek: "Sabzavotlar",
    category: "Food & Dining",
    description: "Vegetables used in plov and traditional soups.",
    keyVocabulary: [
      { uzbek: "sabzi", english: "carrot (yellow/orange)" },
      { uzbek: "piyoz", english: "onion" },
      { uzbek: "kartoshka", english: "potato" },
      { uzbek: "pomidor", english: "tomato" },
      { uzbek: "bodring", english: "cucumber" },
    ],
    grammarFocus: "Yellow carrots (sariq sabzi) are the essential ingredient in authentic Uzbek plov.",
  },
  {
    order: 45,
    level: "A1",
    title: "Drinks and Beverages",
    titleUzbek: "Ichimliklar",
    category: "Food & Dining",
    description: "Ordering and drinking water, tea, and juices.",
    keyVocabulary: [
      { uzbek: "suv", english: "water" },
      { uzbek: "choy", english: "tea" },
      { uzbek: "sharbat / sok", english: "juice" },
      { uzbek: "muzdek suv", english: "ice-cold water" },
      { uzbek: "qaynoq suv", english: "boiling / hot water" },
    ],
    grammarFocus: "Pair with 'ichmoq' (to drink): 'Suv ichaman' (I drink water).",
  },
  {
    order: 46,
    level: "A1",
    title: "Uzbek Bread Culture",
    titleUzbek: "Non madaniyati va tandir",
    category: "Food & Dining",
    description: "Tandir bread traditions, patir, and the ritual of breaking bread.",
    keyVocabulary: [
      { uzbek: "tandir non", english: "clay-oven flatbread" },
      { uzbek: "patir", english: "rich festive flatbread" },
      { uzbek: "non sindirmoq", english: "to break bread (ritual/meal)" },
      { uzbek: "issiq non", english: "hot freshly-baked bread" },
    ],
    grammarFocus: "Bread is broken by hand with both hands at the table before any meal begins.",
  },
  {
    order: 47,
    level: "A1",
    title: "In the Choyxona (Teahouse)",
    titleUzbek: "Choyxonada",
    category: "Culture & Places",
    description: "Teahouse vocabulary, green tea, teapots, and piyola bowls.",
    keyVocabulary: [
      { uzbek: "choyxona", english: "traditional teahouse" },
      { uzbek: "ko'k choy", english: "green tea" },
      { uzbek: "qora choy", english: "black tea" },
      { uzbek: "choynak", english: "teapot" },
      { uzbek: "piyola", english: "tea bowl (handleless cup)" },
    ],
    grammarFocus: "Pouring tea 3 times back into the pot is called 'loyta qilish' to brew evenly.",
  },
  {
    order: 48,
    level: "A1",
    title: "Ordering National Dishes",
    titleUzbek: "Milliy taomlarni buyurtma qilish",
    category: "Food & Dining",
    description: "Ordering plov, somsa, and manti in a restaurant.",
    keyVocabulary: [
      { uzbek: "osh / palov", english: "Uzbek pilaf / plov" },
      { uzbek: "somsa", english: "baked meat pastry" },
      { uzbek: "manti", english: "steamed dumplings" },
      { uzbek: "shashlik", english: "skewered grilled meat" },
      { uzbek: "Bir porsiya osh bering", english: "Please give one portion of plov" },
    ],
    grammarFocus: "Measure words: 'bir porsiya' (one portion), 'ikkita somsa' (two somsas).",
  },
  {
    order: 49,
    level: "A1",
    title: "At the Bazaar: Inquiring Prices",
    titleUzbek: "Bozorda: Narx so'rash",
    category: "Everyday Life",
    description: "Asking 'How much does it cost?' at open-air markets.",
    keyVocabulary: [
      { uzbek: "Bu qancha turadi?", english: "How much does this cost?" },
      { uzbek: "narx", english: "price" },
      { uzbek: "qimmat", english: "expensive" },
      { uzbek: "arzon", english: "cheap / inexpensive" },
    ],
    grammarFocus: "'Qancha' means 'how much/how many'. 'Qancha turadi?' is the standard price query.",
  },
  {
    order: 50,
    level: "A1",
    title: "At the Bazaar: Polite Bargaining",
    titleUzbek: "Bozorda savdolashish",
    category: "Everyday Life",
    description: "Friendly bargaining phrases commonly used in Uzbek bazaars.",
    keyVocabulary: [
      { uzbek: "Arzonroq qiling", english: "Make it a bit cheaper, please" },
      { uzbek: "Oxirgi narxi qancha?", english: "What is your final price?" },
      { uzbek: "Bo'lishi shu", english: "This is the lowest I can go" },
      { uzbek: "Kelishtiring", english: "Give me a fair deal" },
    ],
    grammarFocus: "Comparative suffix -roq: 'arzonroq' (a bit cheaper), 'yaxshiroq' (a bit better).",
  },
  {
    order: 51,
    level: "A1",
    title: "Weights and Units of Measure",
    titleUzbek: "O'lchov birliklari",
    category: "Everyday Life",
    description: "Buying by kilogram, piece, or liter.",
    keyVocabulary: [
      { uzbek: "kilogramm / kilo", english: "kilogram" },
      { uzbek: "dona / ta", english: "piece / item counter" },
      { uzbek: "litr", english: "liter" },
      { uzbek: "yarim kilo", english: "half a kilo" },
      { uzbek: "Ikkita non bering", english: "Give me two breads" },
    ],
    grammarFocus: "Counting suffix -ta attaches to numerals: bitta (1), ikkita (2), uchta (3).",
  },
  {
    order: 52,
    level: "A1",
    title: "Money and Payment",
    titleUzbek: "Pul va to'lov",
    category: "Everyday Life",
    description: "Paying in Uzbek so'm with cash or card.",
    keyVocabulary: [
      { uzbek: "so'm", english: "Uzbek soum (currency)" },
      { uzbek: "naqd pul", english: "cash" },
      { uzbek: "plastik karta", english: "bank card" },
      { uzbek: "qaytim", english: "change (money returned)" },
      { uzbek: "Karta orqali to'layman", english: "I will pay by card" },
    ],
    grammarFocus: "Postposition 'orqali' means 'via / through / by means of'.",
  },
  {
    order: 53,
    level: "A1",
    title: "Locative Case (-da)",
    titleUzbek: "O'rin-payt kelishigi (-da)",
    category: "Grammar Essentials",
    description: "Indicating location: in, at, on with the suffix -da.",
    keyVocabulary: [
      { uzbek: "uyda", english: "at home" },
      { uzbek: "ishda", english: "at work" },
      { uzbek: "Toshkentda", english: "in Tashkent" },
      { uzbek: "stolda", english: "on the table" },
    ],
    grammarFocus: "The locative suffix -da answers questions 'Qayerda?' (Where at?) and 'Qachon?' (When?).",
  },
  {
    order: 54,
    level: "A1",
    title: "Dative Case (-ga)",
    titleUzbek: "Jo'nalish kelishigi (-ga)",
    category: "Grammar Essentials",
    description: "Indicating destination and recipient: to, towards, for.",
    keyVocabulary: [
      { uzbek: "uyga", english: "to home / towards home" },
      { uzbek: "maktabga", english: "to school" },
      { uzbek: "bozorga", english: "to the bazaar" },
      { uzbek: "do'stimga", english: "to my friend" },
    ],
    grammarFocus: "-ga answers 'Qayerga?' (Where to?) and undergoes consonant harmony: -ka after k, -qa after q.",
  },
  {
    order: 55,
    level: "A1",
    title: "Ablative Case (-dan)",
    titleUzbek: "Chiqish kelishigi (-dan)",
    category: "Grammar Essentials",
    description: "Indicating origin, departure, and comparison: from, out of, than.",
    keyVocabulary: [
      { uzbek: "ishdan", english: "from work" },
      { uzbek: "Amerikadan", english: "from America" },
      { uzbek: "uyidan", english: "from his/her house" },
      { uzbek: "sizdan", english: "from you" },
    ],
    grammarFocus: "The ablative suffix -dan answers 'Qayerdan?' (Where from?) and 'Kimdan?' (From whom?).",
  },
  {
    order: 56,
    level: "A1",
    title: "Accusative Case (-ni)",
    titleUzbek: "Tushum kelishigi (-ni)",
    category: "Grammar Essentials",
    description: "Marking the direct, definite object of a sentence.",
    keyVocabulary: [
      { uzbek: "kitobni o'qimoq", english: "to read the book" },
      { uzbek: "nonni olmoq", english: "to take the bread" },
      { uzbek: "Alini ko'rmoq", english: "to see Ali" },
      { uzbek: "Sizni yaxshi ko'raman", english: "I love you / like you" },
    ],
    grammarFocus: "Indefinite objects take no suffix ('Kitob o'qidim'), while definite objects require -ni.",
  },
  {
    order: 57,
    level: "A1",
    title: "Spatial Postpositions: Above, Below, Inside",
    titleUzbek: "O'rin munosabatlari: Ustida, Tagida, Ichida",
    category: "Grammar Essentials",
    description: "Expressing position using locational nouns.",
    keyVocabulary: [
      { uzbek: "ustida", english: "on / on top of" },
      { uzbek: "tagida", english: "under / beneath" },
      { uzbek: "ichida", english: "inside of" },
      { uzbek: "stol ustida", english: "on the table" },
      { uzbek: "sumka ichida", english: "inside the bag" },
    ],
    grammarFocus: "Constructed with genitive + possessive locative: stol(ning) ust-i-da.",
  },
  {
    order: 58,
    level: "A1",
    title: "Spatial Postpositions: In Front, Behind, Next To",
    titleUzbek: "Oldida, Orqasida, Yonida",
    category: "Grammar Essentials",
    description: "Describing proximity and relative positions.",
    keyVocabulary: [
      { uzbek: "oldida", english: "in front of" },
      { uzbek: "orqasida", english: "behind" },
      { uzbek: "yonida", english: "beside / next to" },
      { uzbek: "o'rtasida", english: "between / in the middle of" },
    ],
    grammarFocus: "'Uy yonida' = next to the house; 'Maktab oldida' = in front of the school.",
  },
  {
    order: 59,
    level: "A1",
    title: "Asking and Giving Directions",
    titleUzbek: "Yo'l so'rash va ko'rsatish",
    category: "Travel & Places",
    description: "Navigating streets with left, right, and straight.",
    keyVocabulary: [
      { uzbek: "to'g'riga", english: "straight ahead" },
      { uzbek: "chapga", english: "to the left" },
      { uzbek: "o'ngga", english: "to the right" },
      { uzbek: "buriling", english: "turn! (polite)" },
      { uzbek: "yo'l", english: "road / street / path" },
    ],
    grammarFocus: "Directions take the dative suffix -ga: chap + ga = to the left.",
  },
  {
    order: 60,
    level: "A1",
    title: "City Transportation: Bus & Metro",
    titleUzbek: "Shahar transporti: Avtobus va Metro",
    category: "Travel & Places",
    description: "Using Tashkent's stunning metro and public buses.",
    keyVocabulary: [
      { uzbek: "avtobus", english: "bus" },
      { uzbek: "metro bekati", english: "metro station" },
      { uzbek: "chipta", english: "ticket" },
      { uzbek: "Bu avtobus qayerga boradi?", english: "Where does this bus go?" },
      { uzbek: "keyingi bekat", english: "next station/stop" },
    ],
    grammarFocus: "Verb 'chiqmoq' (to board/get on) + dative: 'Avtobusga chiqmoq'.",
  },
  {
    order: 61,
    level: "A1",
    title: "Taking a Taxi in the City",
    titleUzbek: "Shaharda taksi to'xtatish",
    category: "Travel & Places",
    description: "Hailing a cab or using taxi apps like Yandex Go.",
    keyVocabulary: [
      { uzbek: "taksi", english: "taxi" },
      { uzbek: "Markazga qanchaga borasiz?", english: "How much to take me to the center?" },
      { uzbek: "Shu yerda to'xtating", english: "Please stop right here" },
      { uzbek: "manzil", english: "address / destination" },
    ],
    grammarFocus: "Notice 'qanchaga borasiz?' uses dative suffix -ga ('for how much will you go?').",
  },
  {
    order: 62,
    level: "A1",
    title: "Describing the Weather",
    titleUzbek: "Ob-havoni tasvirlash",
    category: "Everyday Life",
    description: "Sun, rain, snow, heat, and cold in Uzbek.",
    keyVocabulary: [
      { uzbek: "ob-havo", english: "weather" },
      { uzbek: "quyoshli", english: "sunny" },
      { uzbek: "yomg'ir yog'yapti", english: "it is raining" },
      { uzbek: "qor yog'yapti", english: "it is snowing" },
      { uzbek: "issiq / sovuq", english: "hot / cold" },
    ],
    grammarFocus: "Weather phenomena use the verb 'yog'moq' (to precipitate/fall from sky).",
  },
  {
    order: 63,
    level: "A1",
    title: "Present-Future Tense: Affirmative",
    titleUzbek: "Hozirgi-kelasi zamon: Tasdiq",
    category: "Grammar Essentials",
    description: "Forming regular habits and future actions with -a / -y.",
    keyVocabulary: [
      { uzbek: "o'qiyman", english: "I read / I will read" },
      { uzbek: "yozasan", english: "you write / will write" },
      { uzbek: "boradi", english: "he/she goes / will go" },
      { uzbek: "ishlaymiz", english: "we work / will work" },
    ],
    grammarFocus: "Consonant verb stems take -a; vowel stems take -y. Then add personal endings (-man, -san, -di, -miz, -siz, -dilar).",
  },
  {
    order: 64,
    level: "A1",
    title: "Present-Future Tense: Negative",
    titleUzbek: "Hozirgi-kelasi zamon: Inkor",
    category: "Grammar Essentials",
    description: "Negating verbs in the present-future with -may.",
    keyVocabulary: [
      { uzbek: "bormayman", english: "I do not go / will not go" },
      { uzbek: "ichmaysan", english: "you do not drink" },
      { uzbek: "bilmaydi", english: "he/she does not know" },
      { uzbek: "gapirmaymiz", english: "we do not speak" },
    ],
    grammarFocus: "Add negative marker -may directly to verb stem: bor + may + man.",
  },
  {
    order: 65,
    level: "A1",
    title: "Present-Future Tense: Questions",
    titleUzbek: "Hozirgi-kelasi zamon: So'roq shakli",
    category: "Grammar Essentials",
    description: "Asking questions about habits and plans with -asizmi / -asanmi.",
    keyVocabulary: [
      { uzbek: "Choy ichasizmi?", english: "Will you drink tea? / Do you drink tea?" },
      { uzbek: "O'zbekcha bilasizmi?", english: "Do you know Uzbek?" },
      { uzbek: "Ertaga kelasizmi?", english: "Will you come tomorrow?" },
    ],
    grammarFocus: "The clitic -mi appends to the personal suffix: bor + a + siz + mi = borasizmi?",
  },
  {
    order: 66,
    level: "A1",
    title: "Waking Up & Morning Routine",
    titleUzbek: "Uyg'onish va ertalabki tartib",
    category: "Everyday Life",
    description: "Verbs for waking up, getting up, and washing.",
    keyVocabulary: [
      { uzbek: "uyg'onmoq", english: "to wake up" },
      { uzbek: "o'rindan turmoq", english: "to get out of bed" },
      { uzbek: "yuvinmoq", english: "to wash oneself" },
      { uzbek: "tish yuvmoq", english: "to brush teeth" },
      { uzbek: "kiyinmoq", english: "to get dressed" },
    ],
    grammarFocus: "Reflexive suffix -in: 'yuvmoq' (to wash sth) -> 'yuvinmoq' (to wash oneself).",
  },
  {
    order: 67,
    level: "A1",
    title: "Having Breakfast",
    titleUzbek: "Nonushta qilish",
    category: "Food & Dining",
    description: "Talking about morning food and tea.",
    keyVocabulary: [
      { uzbek: "nonushta qilmoq", english: "to have breakfast" },
      { uzbek: "asal", english: "honey" },
      { uzbek: "sariyog'", english: "butter" },
      { uzbek: "pishloq", english: "cheese" },
      { uzbek: "shirin choy", english: "sweet tea" },
    ],
    grammarFocus: "Compound verb 'nonushta qilmoq' pairs a noun with auxiliary 'qilmoq' (to do).",
  },
  {
    order: 68,
    level: "A1",
    title: "Going to Work or University",
    titleUzbek: "Ishga yoki o'qishga borish",
    category: "Everyday Life",
    description: "Commuting and daily schedules.",
    keyVocabulary: [
      { uzbek: "ishga bormoq", english: "to go to work" },
      { uzbek: "o'qishga bormoq", english: "to go to university/school" },
      { uzbek: "dars boshlanadi", english: "class begins" },
      { uzbek: "erta / kech", english: "early / late" },
    ],
    grammarFocus: "Verbs of motion require the dative suffix -ga on destination: ish + ga = ishga.",
  },
  {
    order: 69,
    level: "A1",
    title: "Evening Activities and Relaxation",
    titleUzbek: "Kechki hordiq va dam olish",
    category: "Everyday Life",
    description: "Winding down after a busy day.",
    keyVocabulary: [
      { uzbek: "dam olmoq", english: "to rest / relax" },
      { uzbek: "kechki ovqat", english: "dinner / supper" },
      { uzbek: "kitob o'qimoq", english: "to read a book" },
      { uzbek: "uxlamoq", english: "to sleep" },
      { uzbek: "xayrli tun", english: "good night" },
    ],
    grammarFocus: "'Dam olmoq' literally means 'to take breath / rest'.",
  },
  {
    order: 70,
    level: "A1",
    title: "Expressing Likes with Yoqtirmoq",
    titleUzbek: "Yoqtirmoq fe'li",
    category: "Everyday Life",
    description: "Expressing preferences and favorite things.",
    keyVocabulary: [
      { uzbek: "Men o'zbek taomlarini yoqtiraman", english: "I like Uzbek dishes" },
      { uzbek: "Musiqa yoqtirasizmi?", english: "Do you like music?" },
      { uzbek: "yoqtirmoq", english: "to like" },
      { uzbek: "yoqtirmaslik", english: "to dislike" },
    ],
    grammarFocus: "'Yoqtirmoq' takes an accusative object: 'taomlar-ni yoqtiraman'.",
  },
  {
    order: 71,
    level: "A1",
    title: "Expressing Likes with Menga Yoqadi",
    titleUzbek: "Menga yoqadi konstruksiyasi",
    category: "Grammar Essentials",
    description: "Expressing 'It pleases me / I like it' with dative pronouns.",
    keyVocabulary: [
      { uzbek: "Menga bu shahar yoqadi", english: "I like this city (lit. to me it pleases)" },
      { uzbek: "Sizga yoqdimi?", english: "Did you like it?" },
      { uzbek: "Menga yoqmaydi", english: "I don't like it" },
    ],
    grammarFocus: "Dative pronoun (menga, sizga) + yoqadi (singular) / yoqadi-lar (plural).",
  },
  {
    order: 72,
    level: "A1",
    title: "Wanting Things with Xohlamoq",
    titleUzbek: "Xohlamoq (Istak bildirish)",
    category: "Grammar Essentials",
    description: "Expressing desires and wishes with 'xohlamoq'.",
    keyVocabulary: [
      { uzbek: "Men choy xohlayman", english: "I want tea" },
      { uzbek: "Nima xohlaysiz?", english: "What do you want?" },
      { uzbek: "xohlamoq", english: "to want / desire" },
      { uzbek: "istamoq", english: "to wish / want" },
    ],
    grammarFocus: "'Xohlamoq' pairs with an infinitive in -ish or noun in accusative: 'Borishni xohlayman'.",
  },
  {
    order: 73,
    level: "A1",
    title: "Intention with -moqchi",
    titleUzbek: "-moqchi (Niyat qo'shimchasi)",
    category: "Grammar Essentials",
    description: "Expressing plans: 'I intend to / I am going to...'.",
    keyVocabulary: [
      { uzbek: "Men Samarqandga bormoqchiman", english: "I intend to go to Samarkand" },
      { uzbek: "Nima qilmoqchisiz?", english: "What are you intending to do?" },
      { uzbek: "o'rganmoqchiman", english: "I intend to learn" },
    ],
    grammarFocus: "Verb stem + -moqchi + personal ending: bor + moqchi + man.",
  },
  {
    order: 74,
    level: "A1",
    title: "Ability: Can with -a olmoq",
    titleUzbek: "Imkoniyat: -a olmoq",
    category: "Grammar Essentials",
    description: "Expressing physical or learned ability: 'I can...'.",
    keyVocabulary: [
      { uzbek: "Men o'zbekcha gapira olaman", english: "I can speak Uzbek" },
      { uzbek: "Suzishingiz mumkinmi?", english: "Can you swim?" },
      { uzbek: "o'qiy olaman", english: "I can read" },
    ],
    grammarFocus: "Stem + -a/-y + auxiliary 'olmoq': gapir + a + olaman.",
  },
  {
    order: 75,
    level: "A1",
    title: "Inability: Cannot with -a olmaslik",
    titleUzbek: "Imkonsizlik: -a olmaslik",
    category: "Grammar Essentials",
    description: "Saying 'I cannot do something'.",
    keyVocabulary: [
      { uzbek: "Men tushuna olmayman", english: "I cannot understand" },
      { uzbek: "Kela olmayman", english: "I cannot come" },
      { uzbek: "Yordam bera olmayman", english: "I cannot help" },
    ],
    grammarFocus: "Negative form of olmoq: stem + -a/-y + olmayman (e.g. tushun + a + olmayman).",
  },
  {
    order: 76,
    level: "A1",
    title: "Informal Imperatives (Commands)",
    titleUzbek: "Buyruq mayli: Oddiy shakl",
    category: "Grammar Essentials",
    description: "Giving direct instructions to friends or children.",
    keyVocabulary: [
      { uzbek: "Kel!", english: "Come!" },
      { uzbek: "Bor!", english: "Go!" },
      { uzbek: "O'tir!", english: "Sit!" },
      { uzbek: "Qara!", english: "Look!" },
      { uzbek: "Eshit!", english: "Listen!" },
    ],
    grammarFocus: "The bare verb stem is the informal 2nd person singular imperative.",
  },
  {
    order: 77,
    level: "A1",
    title: "Polite Imperatives with -ing",
    titleUzbek: "Xushmuomala buyruq: -ing / -ingiz",
    category: "Grammar Essentials",
    description: "Inviting guests and asking people politely to do things.",
    keyVocabulary: [
      { uzbek: "Keling!", english: "Please come! / Welcome!" },
      { uzbek: "O'tiring!", english: "Please sit down!" },
      { uzbek: "Oling!", english: "Please take / help yourself (to food)!" },
      { uzbek: "Qarang!", english: "Please look!" },
    ],
    grammarFocus: "Add -ing (after consonant) or -ng (after vowel) to soften commands into respectful invitations.",
  },
  {
    order: 78,
    level: "A1",
    title: "Negative Commands with -ma / -mang",
    titleUzbek: "Inkor buyruq: -mang",
    category: "Grammar Essentials",
    description: "Saying 'Don't do that' respectfully.",
    keyVocabulary: [
      { uzbek: "Xavotir olmang", english: "Don't worry" },
      { uzbek: "Kech qolmang", english: "Don't be late" },
      { uzbek: "Unutmang", english: "Don't forget" },
      { uzbek: "Shoshilmang", english: "Don't rush / Take your time" },
    ],
    grammarFocus: "Negative imperative adds -ma (informal) or -mang (polite) to stem.",
  },
  {
    order: 79,
    level: "A1",
    title: "Making Requests with Iltimos",
    titleUzbek: "Iltimos bilan murojaat",
    category: "Foundations",
    description: "Politely asking for assistance or items.",
    keyVocabulary: [
      { uzbek: "Iltimos, yordam bering", english: "Please, help me" },
      { uzbek: "Iltimos, takrorlang", english: "Please repeat" },
      { uzbek: "Iltimos, sekinroq gapiring", english: "Please speak more slowly" },
      { uzbek: "yordam", english: "help" },
    ],
    grammarFocus: "'Sekinroq' (more slowly) is formed with the softening comparative suffix -roq.",
  },
  {
    order: 80,
    level: "A1",
    title: "Telephone Greetings & Answers",
    titleUzbek: "Telefonda salomlashish",
    category: "Everyday Life",
    description: "Answering the phone and basic phone etiquette.",
    keyVocabulary: [
      { uzbek: "Alo, eshityapman", english: "Hello, I am listening" },
      { uzbek: "Kim gapiryapti?", english: "Who is speaking?" },
      { uzbek: "Ovozingiz yaxshi kelmayapti", english: "Your voice isn't coming through well" },
      { uzbek: "Qaytadan qo'ng'iroq qilaman", english: "I will call back again" },
    ],
    grammarFocus: "'Qo'ng'iroq qilmoq' means 'to make a phone call' (lit. to ring a bell).",
  },
  {
    order: 81,
    level: "A1",
    title: "Making an Appointment",
    titleUzbek: "Uchrashuv belgilash",
    category: "Everyday Life",
    description: "Agreeing on a meeting time and place.",
    keyVocabulary: [
      { uzbek: "Qachon ko'rishamiz?", english: "When shall we meet?" },
      { uzbek: "Soat beshda qulaymi?", english: "Is 5 o'clock convenient?" },
      { uzbek: "qulay", english: "convenient / comfortable" },
      { uzbek: "Kelishdik!", english: "Agreed! / It's a deal!" },
    ],
    grammarFocus: "Reciprocal verb 'ko'rishmoq' (to see each other / meet) from 'ko'rmoq' (to see).",
  },
  {
    order: 82,
    level: "A1",
    title: "Weekend Plans",
    titleUzbek: "Dam olish kunlari rejalari",
    category: "Everyday Life",
    description: "Discussing Saturday and Sunday plans with friends.",
    keyVocabulary: [
      { uzbek: "Dam olish kuni nima qilasiz?", english: "What will you do on the weekend?" },
      { uzbek: "Tog'ga bormoqchimiz", english: "We intend to go to the mountains" },
      { uzbek: "tog'", english: "mountain" },
      { uzbek: "boqqa bormoq", english: "to go to the park / garden" },
    ],
    grammarFocus: "Destination takes dative: tog' + ga = tog'ga (to the mountain).",
  },
  {
    order: 83,
    level: "A1",
    title: "Basic Emotional States",
    titleUzbek: "His-tuyg'ular va holatlar",
    category: "Vocabulary",
    description: "Expressing feelings: happy, sad, tired, hungry, thirsty.",
    keyVocabulary: [
      { uzbek: "xursand", english: "happy / glad" },
      { uzbek: "xafa", english: "sad / upset" },
      { uzbek: "charchagan", english: "tired" },
      { uzbek: "och", english: "hungry" },
      { uzbek: "chanqagan", english: "thirsty" },
    ],
    grammarFocus: "Attach predicative endings: 'Men charchadim' (I got tired) or 'Men charchaganman'.",
  },
  {
    order: 84,
    level: "A1",
    title: "Expressing Physical Health",
    titleUzbek: "Salomatlik holati",
    category: "Everyday Life",
    description: "Stating if you feel ill or healthy.",
    keyVocabulary: [
      { uzbek: "kasalman / betobman", english: "I am sick" },
      { uzbek: "sog'lomman", english: "I am healthy" },
      { uzbek: "Boshim og'riyapti", english: "My head is aching" },
      { uzbek: "og'rimoq", english: "to ache / hurt" },
    ],
    grammarFocus: "Body part + possessive + og'riyapti: 'Qornim og'riyapti' (My stomach hurts).",
  },
  {
    order: 85,
    level: "A1",
    title: "Buying Souvenirs",
    titleUzbek: "Esdalik sovg'alar xarid qilish",
    category: "Culture & Places",
    description: "Selecting Uzbek ceramic bowls, silk scarves, and handmade items.",
    keyVocabulary: [
      { uzbek: "esdalik sovg'a", english: "souvenir" },
      { uzbek: "sopol lagan", english: "ceramic platter" },
      { uzbek: "ipak ro'mol", english: "silk scarf" },
      { uzbek: "qo'lda yasalgan", english: "handmade" },
    ],
    grammarFocus: "'Qo'lda yasalgan' uses locative -da ('made by hand').",
  },
  {
    order: 86,
    level: "A1",
    title: "In a Modern Supermarket",
    titleUzbek: "Zamonaviy supermarketda",
    category: "Everyday Life",
    description: "Basket, checkout, receipt, and packaging.",
    keyVocabulary: [
      { uzbek: "savatcha", english: "shopping basket" },
      { uzbek: "kassa", english: "cash register / checkout" },
      { uzbek: "chek", english: "receipt" },
      { uzbek: "paket", english: "plastic shopping bag" },
    ],
    grammarFocus: "Diminutive suffix -cha in 'savatcha' indicates a small basket (savat = basket).",
  },
  {
    order: 87,
    level: "A1",
    title: "Describing Your House",
    titleUzbek: "Uyimni tasvirlash",
    category: "Everyday Life",
    description: "Talking about your home: spacious, bright, comfortable.",
    keyVocabulary: [
      { uzbek: "keng", english: "spacious / wide" },
      { uzbek: "yorug'", english: "bright / well-lit" },
      { uzbek: "shinam", english: "cozy / comfortable" },
      { uzbek: "hovli", english: "courtyard / yard" },
    ],
    grammarFocus: "Traditional Uzbek homes feature a central 'hovli' (courtyard garden).",
  },
  {
    order: 88,
    level: "A1",
    title: "Describing Your Hometown",
    titleUzbek: "Tug'ilib o'sgan shahrim",
    category: "Culture & Places",
    description: "Describing where you were born and raised.",
    keyVocabulary: [
      { uzbek: "tug'ilgan joyim", english: "my birthplace" },
      { uzbek: "qadimiy shahar", english: "ancient city" },
      { uzbek: "chiroyli ko'chalar", english: "beautiful streets" },
      { uzbek: "tinch", english: "quiet / peaceful" },
    ],
    grammarFocus: "Participle 'tug'ilgan' (born) acts as an adjective modifying 'joyim' (my place).",
  },
  {
    order: 89,
    level: "A1",
    title: "Ordinal Numbers (-inchi)",
    titleUzbek: "Tartib sonlar (-inchi)",
    category: "Foundations",
    description: "Forming first, second, third with -inchi.",
    keyVocabulary: [
      { uzbek: "birinchi", english: "first" },
      { uzbek: "ikkinchi", english: "second" },
      { uzbek: "uchinchi", english: "third" },
      { uzbek: "to'rtinchi", english: "fourth" },
      { uzbek: "beshinchi qavat", english: "fifth floor" },
    ],
    grammarFocus: "Suffix -inchi attaches after consonants; -nchi after vowels (ikkinchi, yettinchi).",
  },
  {
    order: 90,
    level: "A1",
    title: "Conjunctions: And & Or",
    titleUzbek: "Bog'lovchilar: Va, Hamda, Yoki",
    category: "Grammar Essentials",
    description: "Connecting words and clauses with va, hamda, and yoki.",
    keyVocabulary: [
      { uzbek: "va", english: "and" },
      { uzbek: "hamda", english: "and also / as well as" },
      { uzbek: "yoki", english: "or" },
      { uzbek: "Choy yoki qahva?", english: "Tea or coffee?" },
    ],
    grammarFocus: "'Va' joins nouns and clauses; 'yoki' presents alternatives.",
  },
  {
    order: 91,
    level: "A1",
    title: "Conjunctions: But (Lekin, Ammo)",
    titleUzbek: "Bog'lovchilar: Lekin, Ammo",
    category: "Grammar Essentials",
    description: "Expressing contrast in thoughts.",
    keyVocabulary: [
      { uzbek: "lekin", english: "but / however" },
      { uzbek: "ammo", english: "but / yet" },
      { uzbek: "O'zbekcha o'qiyman, lekin tez emas", english: "I read Uzbek, but not quickly" },
    ],
    grammarFocus: "Lekin and ammo are interchangeable in everyday speech.",
  },
  {
    order: 92,
    level: "A1",
    title: "Conjunctions: Because (Chunki)",
    titleUzbek: "Sabab bog'lovchisi: Chunki",
    category: "Grammar Essentials",
    description: "Giving reasons with 'chunki'.",
    keyVocabulary: [
      { uzbek: "chunki", english: "because" },
      { uzbek: "Chunki u charchagan", english: "Because he is tired" },
      { uzbek: "sabab", english: "reason / cause" },
    ],
    grammarFocus: "'Chunki' introduces the subordinate clause providing the justification.",
  },
  {
    order: 93,
    level: "A1",
    title: "Temporal Adverbs: Today, Yesterday, Tomorrow",
    titleUzbek: "Vaqt ravishlari: Bugun, Kecha, Ertaga",
    category: "Everyday Life",
    description: "Key words for anchoring events in time.",
    keyVocabulary: [
      { uzbek: "bugun", english: "today" },
      { uzbek: "kecha", english: "yesterday" },
      { uzbek: "ertaga", english: "tomorrow" },
      { uzbek: "hozir", english: "now" },
      { uzbek: "keyin", english: "later / after" },
    ],
    grammarFocus: "Temporal adverbs usually appear near the start of the clause.",
  },
  {
    order: 94,
    level: "A1",
    title: "Parts of the Day",
    titleUzbek: "Kun qismlari",
    category: "Everyday Life",
    description: "Morning, afternoon, evening, and night.",
    keyVocabulary: [
      { uzbek: "ertalab", english: "in the morning" },
      { uzbek: "kunduzi", english: "during the day" },
      { uzbek: "kechqurun", english: "in the evening" },
      { uzbek: "kechasi", english: "at night" },
    ],
    grammarFocus: "No prepositions needed: 'ertalab kelaman' (I will come in the morning).",
  },
  {
    order: 95,
    level: "A1",
    title: "Welcoming a Guest (Xush Kelibsiz)",
    titleUzbek: "Mehmon kutib olish",
    category: "Culture & Places",
    description: "Hospitality phrases when visitors enter your home.",
    keyVocabulary: [
      { uzbek: "Xush kelibsiz!", english: "Welcome!" },
      { uzbek: "To'rga o'ting!", english: "Please take the place of honor!" },
      { uzbek: "mehmon", english: "guest" },
      { uzbek: "xush ko'rdik", english: "glad to see you (guest response)" },
    ],
    grammarFocus: "'To'r' is the seat of honor furthest from the door, offered to guests and elders.",
  },
  {
    order: 96,
    level: "A1",
    title: "Offering Food at the Table",
    titleUzbek: "Dasturxonga taklif qilish",
    category: "Culture & Places",
    description: "Encouraging guests to taste food and enjoy tea.",
    keyVocabulary: [
      { uzbek: "dasturxon", english: "tablecloth / laid banquet table" },
      { uzbek: "Oling, oling!", english: "Please eat / have more!" },
      { uzbek: "Taomdan tatib ko'ring", english: "Please taste this dish" },
      { uzbek: "to'ydim", english: "I am full / satisfied" },
    ],
    grammarFocus: "Saying 'Oling, oling' twice is an affectionate, insistent hospitality gesture.",
  },
  {
    order: 97,
    level: "A1",
    title: "Expressing Agreement & Disagreement",
    titleUzbek: "Fikrga qo'shilish va rad etish",
    category: "Foundations",
    description: "Agreeing politely or expressing different views.",
    keyVocabulary: [
      { uzbek: "To'g'ri", english: "Correct / Right" },
      { uzbek: "Men ham shunday deb o'ylayman", english: "I think so too" },
      { uzbek: "Menimcha, unday emas", english: "In my opinion, it is not so" },
      { uzbek: "Albatta", english: "Of course / Certainly" },
    ],
    grammarFocus: "Suffix -cha on pronouns expresses perspective: 'menimcha' (in my view).",
  },
  {
    order: 98,
    level: "A1",
    title: "Congratulating Someone",
    titleUzbek: "Tabriklash va qutlash",
    category: "Everyday Life",
    description: "Wishing happy birthday, holidays, and good fortune.",
    keyVocabulary: [
      { uzbek: "Tabriklayman!", english: "Congratulations! / Happy celebration!" },
      { uzbek: "Tug'ilgan kuningiz bilan!", english: "Happy Birthday!" },
      { uzbek: "Bayramingiz muborak bo'lsin!", english: "Happy Holiday! (Blessed holiday)" },
      { uzbek: "Omad tilayman!", english: "I wish you good luck!" },
    ],
    grammarFocus: "Postposition 'bilan' (with) combines with holidays: 'Bayram bilan!' (Happy holiday!).",
  },
  {
    order: 99,
    level: "A1",
    title: "Asking for Clarification",
    titleUzbek: "Tushunmaganda so'rash",
    category: "Foundations",
    description: "What to say when you do not understand native speakers.",
    keyVocabulary: [
      { uzbek: "Men tushunmadim", english: "I did not understand" },
      { uzbek: "Bu nima degani?", english: "What does this mean?" },
      { uzbek: "Yana bir bor ayting", english: "Please say it once more" },
      { uzbek: "Yozib bera olasizmi?", english: "Could you write it down for me?" },
    ],
    grammarFocus: "'Bu nima degani?' literally translates to 'What is the saying of this?'.",
  },
  {
    order: 100,
    level: "A1",
    title: "A1 Capstone: Comprehensive Self-Introduction",
    titleUzbek: "A1 Xulosa: O'zim haqimda to'liq suhbat",
    category: "Foundations",
    description: "Putting together greetings, origin, age, family, job, and hobbies in a fluent self-introduction.",
    keyVocabulary: [
      { uzbek: "o'zim haqimda", english: "about myself" },
      { uzbek: "qiziqishlarim", english: "my interests / hobbies" },
      { uzbek: "maqsadim", english: "my goal" },
      { uzbek: "O'zbekistonda yashayman", english: "I live in Uzbekistan" },
    ],
    grammarFocus: "Combines predicative suffixes, possessives, and locatives in a coherent paragraph.",
  },
  {
    order: 101, level: "A1", title: "A1 Review: Core Conversations", titleUzbek: "A1 takrorlash: Asosiy suhbatlar", category: "Review", description: "Review greetings, introductions, questions, and everyday replies.", keyVocabulary: [{ uzbek: "takrorlash", english: "review" }, { uzbek: "suhbat", english: "conversation" }, { uzbek: "savol", english: "question" }, { uzbek: "javob", english: "answer" }], grammarFocus: "Combine familiar present-tense patterns in short exchanges.",
  },
  {
    order: 102, level: "A1", title: "A1 Review: Shopping & Food", titleUzbek: "A1 takrorlash: Xarid va ovqat", category: "Review", description: "Handle a simple market or cafe interaction from start to finish.", keyVocabulary: [{ uzbek: "narx", english: "price" }, { uzbek: "buyurtma", english: "order" }, { uzbek: "mazali", english: "delicious" }, { uzbek: "hisob", english: "bill" }], grammarFocus: "Practice quantities, polite requests, and basic case endings.",
  },
  {
    order: 103, level: "A1", title: "A1 Review: Home & Family", titleUzbek: "A1 takrorlash: Uy va oila", category: "Review", description: "Describe your home, family members, and daily life.", keyVocabulary: [{ uzbek: "oila", english: "family" }, { uzbek: "xona", english: "room" }, { uzbek: "yaqin", english: "close" }, { uzbek: "birga", english: "together" }], grammarFocus: "Use possessive suffixes and locative phrases confidently.",
  },
  {
    order: 104, level: "A1", title: "A1 Review: Directions & Travel", titleUzbek: "A1 takrorlash: Yo'l va sayohat", category: "Review", description: "Ask for and understand straightforward directions.", keyVocabulary: [{ uzbek: "yo'l", english: "way" }, { uzbek: "chap", english: "left" }, { uzbek: "o'ng", english: "right" }, { uzbek: "bekat", english: "stop" }], grammarFocus: "Use imperative and location forms for navigation.",
  },
  {
    order: 105, level: "A1", title: "A1 Final Can-Do Check", titleUzbek: "A1 yakuniy ko'nikmalar tekshiruvi", category: "Capstone", description: "Demonstrate survival Uzbek in a connected, real-life role play.", keyVocabulary: [{ uzbek: "qila olaman", english: "I can do" }, { uzbek: "mustaqil", english: "independently" }, { uzbek: "muloqot", english: "communication" }, { uzbek: "tayyor", english: "ready" }], grammarFocus: "Integrate A1 vocabulary, polite forms, and simple tenses.",
  },
];
