import type { CurriculumTopic } from "./types";

export const A2_TOPICS: CurriculumTopic[] = [
  {
    order: 1,
    level: "A2",
    title: "Past Definite Tense (-di): Form & Affirmation",
    titleUzbek: "O'tgan aniq zamon (-di): Tasdiq",
    category: "Grammar Essentials",
    description: "Learn to narrate witnessed, definite completed actions in the past.",
    keyVocabulary: [
      { uzbek: "bordim", english: "I went" },
      { uzbek: "ko'rding", english: "you saw" },
      { uzbek: "yozdi", english: "he/she wrote" },
      { uzbek: "keldik", english: "we came" },
    ],
    grammarFocus: "Stem + -di + personal endings: bordim, bording, bordi, bordik, bordingiz, bordilar.",
  },
  {
    order: 2,
    level: "A2",
    title: "Past Definite Tense: Negation & Questions",
    titleUzbek: "O'tgan aniq zamon: Inkor va so'roq",
    category: "Grammar Essentials",
    description: "Negating past events with -madi and asking past questions with -dimi.",
    keyVocabulary: [
      { uzbek: "bormadim", english: "I did not go" },
      { uzbek: "ko'rmadingmi?", english: "didn't you see?" },
      { uzbek: "eshitmadilar", english: "they did not hear" },
      { uzbek: "keldimi?", english: "did he/she come?" },
    ],
    grammarFocus: "Negative stem + -ma + -di + personal suffix: bor + ma + di + m = bormadim.",
  },
  {
    order: 3,
    level: "A2",
    title: "Indefinite & Resultative Past (-gan)",
    titleUzbek: "O'tgan noaniq zamon (-gan)",
    category: "Grammar Essentials",
    description: "Expressing life experiences ('Have you ever...') and past events with present results.",
    keyVocabulary: [
      { uzbek: "Men Samarqandda bo'lganman", english: "I have been to Samarkand" },
      { uzbek: "Bu filmni ko'rganmisiz?", english: "Have you seen this movie?" },
      { uzbek: "o'qiganman", english: "I have read" },
      { uzbek: "ko'rganman", english: "I have seen" },
    ],
    grammarFocus: "Verb stem + -gan/-qan/-kan + predicative ending: bo'l + gan + man.",
  },
  {
    order: 4,
    level: "A2",
    title: "Narrative Past with -ibdi",
    titleUzbek: "Eshitilgan o'tgan zamon (-ibdi)",
    category: "Grammar Essentials",
    description: "Reporting hearsay, stories, or newly discovered past facts.",
    keyVocabulary: [
      { uzbek: "kelibdi", english: "apparently he came / he has arrived" },
      { uzbek: "aytishlaricha", english: "according to what they say" },
      { uzbek: "ketibdi", english: "apparently he has left" },
      { uzbek: "uxlab qolibdi", english: "he fell asleep (unexpectedly)" },
    ],
    grammarFocus: "Stem + -ib + personal ending. Conveys unwitnessed action or sudden surprise.",
  },
  {
    order: 5,
    level: "A2",
    title: "Present Continuous with -yapti",
    titleUzbek: "Hozirgi davom zamon (-yapti)",
    category: "Grammar Essentials",
    description: "Describing actions happening right now at the moment of speech.",
    keyVocabulary: [
      { uzbek: "yozayapman", english: "I am writing right now" },
      { uzbek: "choy ichyapti", english: "he/she is drinking tea right now" },
      { uzbek: "Nima qilyapsiz?", english: "What are you doing right now?" },
      { uzbek: "ishlayapmiz", english: "we are working" },
    ],
    grammarFocus: "Stem + -(a)yap + personal ending: o'qi + yap + man (o'qiyapman).",
  },
  {
    order: 6,
    level: "A2",
    title: "Formal Present Continuous (-moqda)",
    titleUzbek: "Rasmiy davom zamon (-moqda)",
    category: "Grammar Essentials",
    description: "Expressing ongoing continuous actions in written news, articles, and formal speech.",
    keyVocabulary: [
      { uzbek: "qurilmoqda", english: "is being built / is underway" },
      { uzbek: "rivojlanmoqda", english: "is developing" },
      { uzbek: "o'rganmoqdaman", english: "I am currently studying (formal)" },
    ],
    grammarFocus: "Stem + -moqda + personal suffix: rivojlan + moqda.",
  },
  {
    order: 7,
    level: "A2",
    title: "Past Continuous (-ayotgan edi)",
    titleUzbek: "O'tgan davom zamon (-ayotgan edi)",
    category: "Grammar Essentials",
    description: "Describing background actions that were ongoing at a specific time in the past.",
    keyVocabulary: [
      { uzbek: "Men kitob o'qiyotgan edim", english: "I was reading a book (when...)" },
      { uzbek: "Uxlab yotgan edilar", english: "They were sleeping" },
      { uzbek: "yomg'ir yog'ayotgan edi", english: "it was raining" },
    ],
    grammarFocus: "Present continuous participle + auxiliary 'edi' with personal endings.",
  },
  {
    order: 8,
    level: "A2",
    title: "Comparative Adjectives (-roq)",
    titleUzbek: "Qiyosiy daraja (-roq)",
    category: "Grammar Essentials",
    description: "Comparing two items with the suffix -roq and ablative -dan.",
    keyVocabulary: [
      { uzbek: "kattaroq", english: "bigger / larger" },
      { uzbek: "yaxshiroq", english: "better" },
      { uzbek: "Bu uy unikidan kattaroq", english: "This house is bigger than his" },
      { uzbek: "arzonroq", english: "cheaper" },
    ],
    grammarFocus: "Item A + Item B-dan + Adjective-roq: 'Poyezd avtobusdan tezroq' (Train is faster than bus).",
  },
  {
    order: 9,
    level: "A2",
    title: "Superlative Adjectives (Eng, Juda)",
    titleUzbek: "Orttirma daraja: Eng, Juda",
    category: "Grammar Essentials",
    description: "Expressing the highest degree of qualities.",
    keyVocabulary: [
      { uzbek: "eng katta", english: "the biggest / largest" },
      { uzbek: "eng chiroyli", english: "the most beautiful" },
      { uzbek: "juda mazali", english: "very delicious" },
      { uzbek: "nihoyatda", english: "extremely / immensely" },
    ],
    grammarFocus: "'Eng' precedes the adjective to form the superlative; 'juda' intensifies it.",
  },
  {
    order: 10,
    level: "A2",
    title: "Time Clauses with Oldin (Before)",
    titleUzbek: "Vaqt bog'lanishi: -ishdan oldin",
    category: "Grammar Essentials",
    description: "Saying 'before doing something' with verbal nouns + ablative + oldin.",
    keyVocabulary: [
      { uzbek: "ovqatlanishdan oldin", english: "before eating" },
      { uzbek: "ketishdan oldin", english: "before leaving" },
      { uzbek: "uchrashuvdan oldin", english: "before the meeting" },
      { uzbek: "oldin / avval", english: "before / ago" },
    ],
    grammarFocus: "Verb stem + -ish/-sh + -dan oldin: yoz + ish + dan oldin (before writing).",
  },
  {
    order: 11,
    level: "A2",
    title: "Time Clauses with Keyin (After)",
    titleUzbek: "Vaqt bog'lanishi: -gandan keyin / so'ng",
    category: "Grammar Essentials",
    description: "Saying 'after doing something' with past participle + ablative + keyin.",
    keyVocabulary: [
      { uzbek: "dars tugagandan keyin", english: "after the lesson finishes" },
      { uzbek: "kelgandan keyin", english: "after arriving" },
      { uzbek: "ishdan so'ng", english: "after work" },
      { uzbek: "keyin / so'ng", english: "after / afterwards" },
    ],
    grammarFocus: "Verb stem + -gan/-qan + -dan keyin: tugagan + dan keyin.",
  },
  {
    order: 12,
    level: "A2",
    title: "When Doing Something: -ganda",
    titleUzbek: "-ganda qo'shimchasi (Payt ravishdoshi)",
    category: "Grammar Essentials",
    description: "Forming temporal adverbial clauses meaning 'when...'.",
    keyVocabulary: [
      { uzbek: "Toshkentga kelganimda", english: "when I came to Tashkent" },
      { uzbek: "ko'rganingda", english: "when you see/saw" },
      { uzbek: "uyga borganimizda", english: "when we went home" },
    ],
    grammarFocus: "Verb stem + -gan + possessive suffix + -da: kel + gan + im + da.",
  },
  {
    order: 13,
    level: "A2",
    title: "Visiting the Doctor: Booking & Greeting",
    titleUzbek: "Shifokor qabuliga yozilish",
    category: "Health & Well-being",
    description: "Making an appointment at a clinic and greeting the medical provider.",
    keyVocabulary: [
      { uzbek: "poliklinika / klinika", english: "clinic" },
      { uzbek: "qabulga yozilmoq", english: "to make an appointment" },
      { uzbek: "shifokor ko'rigi", english: "doctor examination" },
      { uzbek: "navbat", english: "queue / turn" },
    ],
    grammarFocus: "Use 'navbat olmoq' (to take a queue ticket/turn) at modern medical centers.",
  },
  {
    order: 14,
    level: "A2",
    title: "Explaining Symptoms to the Doctor",
    titleUzbek: "Shifokorga kasallik alomatlarini aytish",
    category: "Health & Well-being",
    description: "Describing pain, fever, cough, and throat ache.",
    keyVocabulary: [
      { uzbek: "haroratim baland", english: "my fever/temperature is high" },
      { uzbek: "tomog'im og'riyapti", english: "my throat hurts" },
      { uzbek: "yo'talyapman", english: "I am coughing" },
      { uzbek: "shamollash", english: "catching a cold" },
      { uzbek: "shamollab qoldim", english: "I caught a cold" },
    ],
    grammarFocus: "Verb 'og'rimoq' (to ache): 'Qayeringiz og'riyapti?' (Where does it hurt?).",
  },
  {
    order: 15,
    level: "A2",
    title: "At the Pharmacy (Dorixona)",
    titleUzbek: "Dorixonada dori xarid qilish",
    category: "Health & Well-being",
    description: "Buying medicines, painkillers, and vitamins.",
    keyVocabulary: [
      { uzbek: "dorixona", english: "pharmacy" },
      { uzbek: "dori", english: "medicine / pill" },
      { uzbek: "og'riq qoldiruvchi dori", english: "painkiller" },
      { uzbek: "retsept", english: "prescription" },
      { uzbek: "Kuniga necha marta ichiladi?", english: "How many times a day should it be taken?" },
    ],
    grammarFocus: "Passive form 'ichiladi' (is to be taken / drank).",
  },
  {
    order: 16,
    level: "A2",
    title: "Describing Physical Appearance: Height & Build",
    titleUzbek: "Tashqi ko'rinish: Bo'y-bast",
    category: "Describing People",
    description: "Describing someone's stature, height, and build.",
    keyVocabulary: [
      { uzbek: "bo'yi baland", english: "tall" },
      { uzbek: "bo'yi past", english: "short in height" },
      { uzbek: "o'rtacha bo'yli", english: "average height" },
      { uzbek: "ozg'in", english: "slim / thin" },
      { uzbek: "semiz / to'ladan kelgan", english: "stout / chubby" },
    ],
    grammarFocus: "Suffix -li forms adjectives from nouns: bo'y (height) + li = bo'yli.",
  },
  {
    order: 17,
    level: "A2",
    title: "Describing Hair and Eyes",
    titleUzbek: "Soch va ko'zlarni tasvirlash",
    category: "Describing People",
    description: "Hair colors, styles, and eye colors.",
    keyVocabulary: [
      { uzbek: "soch", english: "hair" },
      { uzbek: "qora sochli", english: "black-haired" },
      { uzbek: "sariq sochli", english: "blonde / fair-haired" },
      { uzbek: "uzun / kalta soch", english: "long / short hair" },
      { uzbek: "qora ko'zli", english: "dark-eyed" },
      { uzbek: "moviy ko'zli", english: "blue-eyed" },
    ],
    grammarFocus: "Pattern: [Color] + [Body Part] + -li (e.g. jigar-rang ko'zli = brown-eyed).",
  },
  {
    order: 18,
    level: "A2",
    title: "Describing Positive Character Traits",
    titleUzbek: "Ijobiy insoniy fazilatlar",
    category: "Describing People",
    description: "Virtues like generosity, kindness, honesty, and modesty.",
    keyVocabulary: [
      { uzbek: "mehribon", english: "kind / affectionate" },
      { uzbek: "saxiy", english: "generous" },
      { uzbek: "kamtar", english: "humble / modest" },
      { uzbek: "halol / to'g'riso'z", english: "honest / truthful" },
      { uzbek: "mehnatkash", english: "hardworking" },
    ],
    grammarFocus: "The suffix -kash denotes devotion or continuous action (mehnat + kash = hardworking).",
  },
  {
    order: 19,
    level: "A2",
    title: "Describing Difficult Character Traits",
    titleUzbek: "Salbiy fe'l-atvor",
    category: "Describing People",
    description: "Words for stubborn, angry, lazy, and proud personalities.",
    keyVocabulary: [
      { uzbek: "dangasa", english: "lazy" },
      { uzbek: "jahldor", english: "quick-tempered / angry" },
      { uzbek: "qaysar", english: "stubborn" },
      { uzbek: "xasis", english: "stingy / miserly" },
      { uzbek: "maqtanchoq", english: "boastful" },
    ],
    grammarFocus: "Suffix -dor denotes having a quality: jahl (anger) + dor = angry.",
  },
  {
    order: 20,
    level: "A2",
    title: "Uzbek Plov Preparation Secrets",
    titleUzbek: "Osh tayyorlash sirlari",
    category: "Culture & Food",
    description: "Mastering the vocabulary of cooking real Uzbek plov (zirvak, damlash).",
    keyVocabulary: [
      { uzbek: "zirvak", english: "seasoned broth base for plov" },
      { uzbek: "damlamoq", english: "to simmer/steam under lid" },
      { uzbek: "qovurmoq", english: "to fry / sauté" },
      { uzbek: "qo'y go'shti", english: "lamb / mutton" },
      { uzbek: "zira", english: "cumin seeds" },
    ],
    grammarFocus: "Zira (cumin) and sariq sabzi (yellow carrots) are the aromatic soul of Uzbek plov.",
  },
  {
    order: 21,
    level: "A2",
    title: "Somsa and Manti Varieties",
    titleUzbek: "Somsa va manti turlari",
    category: "Culture & Food",
    description: "Tandir somsa, qovoq somsa (pumpkin), and steamed manti.",
    keyVocabulary: [
      { uzbek: "tandir somsa", english: "clay-oven baked somsa" },
      { uzbek: "varaqi somsa", english: "flaky puff pastry somsa" },
      { uzbek: "qovoqli somsa", english: "pumpkin-filled somsa" },
      { uzbek: "qiyma", english: "minced meat filling" },
      { uzbek: "mantiqasqon", english: "multi-tiered steamer pot" },
    ],
    grammarFocus: "Adjectives with -li show filling: go'shtli (with meat), qovoqli (with pumpkin).",
  },
  {
    order: 22,
    level: "A2",
    title: "Lag'mon & Noodle Making",
    titleUzbek: "Lag'mon va cho'zma xamir",
    category: "Culture & Food",
    description: "Hand-pulled Uyghur-Uzbek noodles and rich vegetable gravies.",
    keyVocabulary: [
      { uzbek: "cho'zma lag'mon", english: "hand-pulled noodle lagman" },
      { uzbek: "qovurma lag'mon", english: "fried lagman noodles" },
      { uzbek: "xamir", english: "dough" },
      { uzbek: "bulg'or qalampiri", english: "bell pepper" },
      { uzbek: "achchiq", english: "spicy / hot" },
    ],
    grammarFocus: "Participles 'cho'zma' (pulled) and 'qovurma' (fried) describe the style of noodles.",
  },
  {
    order: 23,
    level: "A2",
    title: "Kitchen Cookware & Utensils",
    titleUzbek: "Oshxona anjomlari",
    category: "Everyday Life",
    description: "Traditional and modern kitchen tools (qozon, cho'mich).",
    keyVocabulary: [
      { uzbek: "qozon", english: "cast-iron cauldron" },
      { uzbek: "cho'mich", english: "large ladle / skimmer" },
      { uzbek: "pichoq", english: "knife" },
      { uzbek: "tova", english: "frying pan" },
      { uzbek: "lagan", english: "large serving platter" },
    ],
    grammarFocus: "A 'qozon' is the sacred hearth fixture of every Uzbek home.",
  },
  {
    order: 24,
    level: "A2",
    title: "Renting an Apartment in Tashkent",
    titleUzbek: "Toshkentda ijara uy topish",
    category: "Everyday Life",
    description: "Searching for rentals, discussing rent price, and conditions.",
    keyVocabulary: [
      { uzbek: "ijara / arenda", english: "rent / lease" },
      { uzbek: "ijaraga olmoq", english: "to rent / take on lease" },
      { uzbek: "ijara haqi", english: "rental payment" },
      { uzbek: "bir xonali kvartira", english: "one-room apartment" },
      { uzbek: "remontli", english: "renovated / furnished" },
    ],
    grammarFocus: "'Ijara haqi' uses the izafet structure: ijara + haq + i (fee of rent).",
  },
  {
    order: 25,
    level: "A2",
    title: "Utilities and Household Maintenance",
    titleUzbek: "Kommunal xizmatlar va to'lovlar",
    category: "Everyday Life",
    description: "Electricity, natural gas, hot water, and internet bills.",
    keyVocabulary: [
      { uzbek: "elektr energiyasi / chiroq", english: "electricity / lights" },
      { uzbek: "tabiiy gaz", english: "natural gas" },
      { uzbek: "issiq suv", english: "hot water" },
      { uzbek: "hisoblagich", english: "meter (utility counter)" },
      { uzbek: "kommunal to'lov", english: "utility payment" },
    ],
    grammarFocus: "'Chiroq o'chdi' colloquially means 'the power went out'.",
  },
  {
    order: 26,
    level: "A2",
    title: "Uzbek Mahalla Culture",
    titleUzbek: "O'zbek mahallasi va an'analar",
    category: "Culture & Society",
    description: "The neighborhood community structure, elders, and collective support.",
    keyVocabulary: [
      { uzbek: "mahalla", english: "neighborhood community" },
      { uzbek: "mahalla oqsoqoli", english: "community elder / head" },
      { uzbek: "qo'shni", english: "neighbor" },
      { uzbek: "hamjihatlik", english: "solidarity / unity" },
    ],
    grammarFocus: "An Uzbek proverb states: 'Qo'shning tinch — sen tinch' (If your neighbor is at peace, you are at peace).",
  },
  {
    order: 27,
    level: "A2",
    title: "The Hashar Tradition",
    titleUzbek: "Hashar — hamjihatlik ramzi",
    category: "Culture & Society",
    description: "Voluntary mutual community cleanups and house-building assistance.",
    keyVocabulary: [
      { uzbek: "hashar", english: "voluntary communal mutual-aid" },
      { uzbek: "hashar qilmoq", english: "to conduct a communal cleanup" },
      { uzbek: "ko'kalamzorlashtirish", english: "greening / planting trees" },
      { uzbek: "obod qilish", english: "making prosperous and beautiful" },
    ],
    grammarFocus: "Hashar is held nationally ahead of Navruz and Independence Day.",
  },
  {
    order: 28,
    level: "A2",
    title: "Afrosiyob High-Speed Train",
    titleUzbek: "Afrosiyob tezyurar poyezdi",
    category: "Travel & Places",
    description: "Booking train tickets to Samarkand, Bukhara, and Qarshi.",
    keyVocabulary: [
      { uzbek: "tezyurar poyezd", english: "high-speed train" },
      { uzbek: "temir yo'l vokzali", english: "railway station" },
      { uzbek: "vagon", english: "train carriage / wagon" },
      { uzbek: "o'rindiq", english: "seat" },
      { uzbek: "jo'nab ketmoq", english: "to depart" },
    ],
    grammarFocus: "Afrosiyob connects Tashkent to Samarkand in just 2 hours and 15 minutes.",
  },
  {
    order: 29,
    level: "A2",
    title: "At the Airport & Checking In",
    titleUzbek: "Aeroportda: Ro'yxatdan o'tish",
    category: "Travel & Places",
    description: "Boarding pass, passport control, and luggage drops.",
    keyVocabulary: [
      { uzbek: "aeroport", english: "airport" },
      { uzbek: "ro'yxatdan o'tish", english: "check-in / registration" },
      { uzbek: "uchish zali", english: "departure hall" },
      { uzbek: "qo'nish", english: "landing / arrival" },
      { uzbek: "yuk / bagaj", english: "baggage / luggage" },
    ],
    grammarFocus: "'Uchib ketmoq' means 'to fly away/depart'; 'qo'nmoq' means 'to land'.",
  },
  {
    order: 30,
    level: "A2",
    title: "Sightseeing in Samarkand: Registan",
    titleUzbek: "Samarqand: Registon maydoni",
    category: "Travel & Places",
    description: "Exploring the three famous madrasahs: Ulugbek, Sher-Dor, and Tilya-Kori.",
    keyVocabulary: [
      { uzbek: "Registon maydoni", english: "Registan Square" },
      { uzbek: "madrasa", english: "Islamic college / historic academy" },
      { uzbek: "koshin / naqsh", english: "glazed tile mosaic / ornament" },
      { uzbek: "tarixiy obida", english: "historic monument" },
    ],
    grammarFocus: "Use 'tomosha qilmoq' (to view / enjoy sightseeing).",
  },
  {
    order: 31,
    level: "A2",
    title: "Exploring Bukhara: Labi Hovuz",
    titleUzbek: "Buxoro: Labi Hovuz ansambli",
    category: "Travel & Places",
    description: "Relaxing around the ancient pond shaded by centuries-old mulberry trees.",
    keyVocabulary: [
      { uzbek: "Labi Hovuz", english: "By the Pond (historic Bukhara square)" },
      { uzbek: "hovuz", english: "historic stone pond/reservoir" },
      { uzbek: "tut daraxti", english: "mulberry tree" },
      { uzbek: "Ark qal'asi", english: "Ark Citadel of Bukhara" },
    ],
    grammarFocus: "The Persian preposition 'lab' in Uzbek means 'edge/bank' ('lab-i hovuz' = pond bank).",
  },
  {
    order: 32,
    level: "A2",
    title: "Exploring Khiva: Ichan Qal'a",
    titleUzbek: "Xiva: Ichan Qal'a muzey-shahri",
    category: "Travel & Places",
    description: "Walking the open-air fortress of Khiva and Kalta Minor minaret.",
    keyVocabulary: [
      { uzbek: "Ichan Qal'a", english: "Inner Fortress of Khiva" },
      { uzbek: "minora", english: "minaret / tower" },
      { uzbek: "somon suvoq", english: "traditional straw-clay plaster" },
      { uzbek: "o'ymakor yog'och ustun", english: "carved wooden pillar" },
    ],
    grammarFocus: "Ichan Qal'a was the first UNESCO World Heritage site recognized in Uzbekistan.",
  },
  {
    order: 33,
    level: "A2",
    title: "At the Post Office: Sending Parcels",
    titleUzbek: "Pochtada posilka jo'natish",
    category: "Everyday Life",
    description: "Mailing letters, buying envelopes, and weighing parcels.",
    keyVocabulary: [
      { uzbek: "pochta", english: "post office" },
      { uzbek: "posilka", english: "parcel / package" },
      { uzbek: "jo'natmoq", english: "to send / dispatch" },
      { uzbek: "konvert", english: "envelope" },
      { uzbek: "marka", english: "postage stamp" },
    ],
    grammarFocus: "Verb 'jo'natmoq' requires dative destination: 'Amerikaga posilka jo'natmoq'.",
  },
  {
    order: 34,
    level: "A2",
    title: "Banking and Currency Exchange",
    titleUzbek: "Bank va valyuta ayirboshlash",
    category: "Everyday Life",
    description: "Exchanging foreign currency for Uzbek soum at bank branches.",
    keyVocabulary: [
      { uzbek: "bank", english: "bank" },
      { uzbek: "valyuta ayirboshlash", english: "currency exchange" },
      { uzbek: "kurs", english: "exchange rate" },
      { uzbek: "AQSH dollari", english: "US Dollar" },
      { uzbek: "almashtirmoq", english: "to exchange / swap" },
    ],
    grammarFocus: "Compound noun 'ayirboshlash shoxobchasi' means 'currency exchange office'.",
  },
  {
    order: 35,
    level: "A2",
    title: "Using Mobile Payments (Payme, Click)",
    titleUzbek: "Mobil to'lov ilovalari",
    category: "Everyday Life",
    description: "Using QR codes, phone transfers, and paying utility bills on mobile.",
    keyVocabulary: [
      { uzbek: "mobil ilova", english: "mobile application" },
      { uzbek: "pul o'tkazmasi", english: "money transfer" },
      { uzbek: "QR kod orqali to'lash", english: "paying via QR code" },
      { uzbek: "kartadan kartaga", english: "card-to-card transfer" },
      { uzbek: "hisobni to'ldirmoq", english: "to top up balance" },
    ],
    grammarFocus: "Uzbekistan is one of the world leaders in seamless QR card-to-card payments.",
  },
  {
    order: 36,
    level: "A2",
    title: "Domestic Animals and Pets",
    titleUzbek: "Uy hayvonlari",
    category: "Nature & Environment",
    description: "Dogs, cats, horses, sheep, and birds.",
    keyVocabulary: [
      { uzbek: "it", english: "dog" },
      { uzbek: "mushuk", english: "cat" },
      { uzbek: "ot", english: "horse" },
      { uzbek: "qo'y", english: "sheep" },
      { uzbek: "sigir", english: "cow" },
      { uzbek: "tovuq", english: "chicken" },
    ],
    grammarFocus: "Diminutives for young animals: 'kuchukcha' (puppy), 'mushukcha' (kitten).",
  },
  {
    order: 37,
    level: "A2",
    title: "Countryside & Village Life",
    titleUzbek: "Qishloq hayoti va dalalar",
    category: "Nature & Environment",
    description: "Agricultural orchards, irrigation canals, and rural routines.",
    keyVocabulary: [
      { uzbek: "qishloq", english: "village / countryside" },
      { uzbek: "dala", english: "field / farmland" },
      { uzbek: "ariq", english: "irrigation ditch / canal" },
      { uzbek: "bog'", english: "orchard / garden" },
      { uzbek: "hosil", english: "harvest / crop" },
    ],
    grammarFocus: "An 'ariq' is the traditional irrigation waterway running through streets and courtyards.",
  },
  {
    order: 38,
    level: "A2",
    title: "Traditional Uzbek Wrestling: Kurash",
    titleUzbek: "O'zbek milliy kurashi",
    category: "Sports & Hobbies",
    description: "Rules, yaktak jackets, and the international status of Kurash.",
    keyVocabulary: [
      { uzbek: "kurash", english: "traditional Uzbek belt wrestling" },
      { uzbek: "polvon", english: "wrestler / strongman / hero" },
      { uzbek: "yaktak", english: "traditional green/blue wrestling jacket" },
      { uzbek: "halol", english: "clean/fair throw (winning score)" },
    ],
    grammarFocus: "'Polvon' is also an affectionate respectful term for any strong, capable young man.",
  },
  {
    order: 39,
    level: "A2",
    title: "Horseback Game: Uloq-Ko'pkari",
    titleUzbek: "Uloq-ko'pkari o'yini",
    category: "Sports & Hobbies",
    description: "The thrilling Central Asian equestrian sport of goat grabbing.",
    keyVocabulary: [
      { uzbek: "uloq / ko'pkari", english: "equestrian goat-grabbing tournament" },
      { uzbek: "chavandoz", english: "skilled horseman / equestrian rider" },
      { uzbek: "tulpor / ot", english: "spirited steed / horse" },
      { uzbek: "sovrin", english: "prize / trophy" },
    ],
    grammarFocus: "Ko'pkari tournaments are traditionally hosted during harvest festivals and weddings.",
  },
  {
    order: 40,
    level: "A2",
    title: "Modern Fitness & Sports Clubs",
    titleUzbek: "Zamonaviy sport va fitnes",
    category: "Sports & Hobbies",
    description: "Gym workouts, running, and football matches.",
    keyVocabulary: [
      { uzbek: "sport zali", english: "gym / sports hall" },
      { uzbek: "mashg'ulot", english: "workout / training session" },
      { uzbek: "yugurmoq", english: "to run" },
      { uzbek: "futbol o'ynamoq", english: "to play football/soccer" },
      { uzbek: "murabbiy", english: "coach / trainer" },
    ],
    grammarFocus: "Play sports using 'o'ynamoq' (e.g. tennis o'ynamoq, shaxmat o'ynamoq).",
  },
  {
    order: 41,
    level: "A2",
    title: "Traditional Uzbek Musical Instruments",
    titleUzbek: "Milliy musiqa asboblari",
    category: "Culture & Arts",
    description: "The two-stringed Dutor, Doira frame drum, and Tanbur.",
    keyVocabulary: [
      { uzbek: "dutor", english: "two-stringed fretted lute" },
      { uzbek: "doira", english: "traditional frame drum with metal rings" },
      { uzbek: "tanbur", english: "long-necked plucked lute" },
      { uzbek: "cholg'u asbobi", english: "musical instrument" },
      { uzbek: "kuy", english: "melody / tune" },
    ],
    grammarFocus: "The verb 'chalmoq' means 'to play a musical instrument' (dutor chalmoq).",
  },
  {
    order: 42,
    level: "A2",
    title: "At the Theatre & Concert Hall",
    titleUzbek: "Teatr va konsertda",
    category: "Culture & Arts",
    description: "Attending opera, ballet, or drama at the Navoi Theater.",
    keyVocabulary: [
      { uzbek: "teatr", english: "theatre" },
      { uzbek: "spektakl", english: "play / theatrical show" },
      { uzbek: "sahna", english: "stage" },
      { uzbek: "aktyor", english: "actor" },
      { uzbek: "qarsaklar", english: "applause / clapping" },
    ],
    grammarFocus: "Alisher Navoi Opera and Ballet Theatre in Tashkent is a masterpiece of Central Asian architecture.",
  },
  {
    order: 43,
    level: "A2",
    title: "Invitations & Wedding Announcements",
    titleUzbek: "Taklifnoma va mehmonga chorlash",
    category: "Social Life",
    description: "Inviting friends to birthday parties, tea, or weddings.",
    keyVocabulary: [
      { uzbek: "taklif qilmoq", english: "to invite" },
      { uzbek: "taklifnoma", english: "invitation card" },
      { uzbek: "to'y", english: "wedding / celebration banquet" },
      { uzbek: "Keling, mehmonga boring!", english: "Come, be our guest!" },
    ],
    grammarFocus: "The Persian-origin suffix -noma means 'written document' (taklif + noma = invitation letter).",
  },
  {
    order: 44,
    level: "A2",
    title: "Accepting & Declining Invitations",
    titleUzbek: "Taklifni qabul qilish va rad etish",
    category: "Social Life",
    description: "Saying yes with pleasure or politely giving excuses.",
    keyVocabulary: [
      { uzbek: "Jon deb kelaman", english: "I will come with great pleasure (lit. saying soul)" },
      { uzbek: "Albatta boraman", english: "I will certainly go" },
      { uzbek: "Uzr, vaqtim yo'q edi", english: "Excuse me, I didn't have time" },
      { uzbek: "Boshqa safar", english: "Another time / Next time" },
    ],
    grammarFocus: "'Jon deb' is a warm idiomatic Uzbek response meaning 'willingly / gladly'.",
  },
  {
    order: 45,
    level: "A2",
    title: "Apologizing: Kechirasiz vs Uzr",
    titleUzbek: "Uzr so'rash va kechirim",
    category: "Social Life",
    description: "Distinguishing degrees of apology.",
    keyVocabulary: [
      { uzbek: "Uzr so'rayman", english: "I apologize" },
      { uzbek: "Aybga buyurmaysiz", english: "Don't hold it against me / forgive my shortcoming" },
      { uzbek: "Hechqisi yo'q", english: "It's nothing / No worries" },
      { uzbek: "Zarari yo'q", english: "No harm done" },
    ],
    grammarFocus: "'Aybga buyurmaysiz' is the ultimate culturally gracious apology among Uzbeks.",
  },
  {
    order: 46,
    level: "A2",
    title: "Necessity & Obligation with Kerak",
    titleUzbek: "Kerak so'zi bilan zaruriyat",
    category: "Grammar Essentials",
    description: "Saying 'I need to / must do something' with verbal nouns + kerak.",
    keyVocabulary: [
      { uzbek: "borishim kerak", english: "I must go (lit. my going is necessary)" },
      { uzbek: "o'qishingiz kerak", english: "you need to read" },
      { uzbek: "nima qilish kerak?", english: "what needs to be done?" },
      { uzbek: "kerak emas", english: "not needed / unnecessary" },
    ],
    grammarFocus: "Pattern: Verb + -ish + possessive ending + kerak: bor + ish + im + kerak.",
  },
  {
    order: 47,
    level: "A2",
    title: "Permission with Mumkin",
    titleUzbek: "Mumkin so'zi bilan ruxsat so'rash",
    category: "Grammar Essentials",
    description: "Asking 'May I...?' and 'Is it permitted?'.",
    keyVocabulary: [
      { uzbek: "Kirsam maylimi? / Mumkinmi?", english: "May I enter?" },
      { uzbek: "Savol bersam mumkinmi?", english: "May I ask a question?" },
      { uzbek: "Mumkin", english: "It is permitted / You may" },
    ],
    grammarFocus: "Conditional verb stem + -sa + possessive + mumkinmi: kir + sa + m + mumkinmi.",
  },
  {
    order: 48,
    level: "A2",
    title: "Prohibition with Mumkin Emas",
    titleUzbek: "Mumkin emas bilan taqiq",
    category: "Grammar Essentials",
    description: "Saying 'It is forbidden / You cannot...'.",
    keyVocabulary: [
      { uzbek: "Bu yerda to'xtash mumkin emas", english: "No parking allowed here" },
      { uzbek: "Ruxsatsiz kirish mumkin emas", english: "No entry without permission" },
      { uzbek: "chekish mumkin emas", english: "smoking is forbidden" },
    ],
    grammarFocus: "Verbal noun (-ish) + mumkin emas: 'Suratga olish mumkin emas' (No photography).",
  },
  {
    order: 49,
    level: "A2",
    title: "Strong Duty with Shart",
    titleUzbek: "Shart so'zi bilan qat'iy majburiyat",
    category: "Grammar Essentials",
    description: "Expressing strict, non-negotiable obligation.",
    keyVocabulary: [
      { uzbek: "kelishingiz shart", english: "you must strictly come" },
      { uzbek: "qoidalarga rioya qilish shart", english: "obeying rules is mandatory" },
      { uzbek: "shart emas", english: "not mandatory / optional" },
    ],
    grammarFocus: "'Shart' expresses stronger, stricter imperative requirement than 'kerak'.",
  },
  {
    order: 50,
    level: "A2",
    title: "Reflexive Verbs (-in / -il)",
    titleUzbek: "O'zlik nisbati (-in)",
    category: "Grammar Essentials",
    description: "Actions performed upon oneself.",
    keyVocabulary: [
      { uzbek: "kiyinmoq", english: "to dress oneself" },
      { uzbek: "yuvinmoq", english: "to wash oneself" },
      { uzbek: "taranmoq", english: "to comb one's hair" },
      { uzbek: "tayyorlanmoq", english: "to prepare oneself" },
    ],
    grammarFocus: "Root kiymoq -> kiyinmoq; yuvmoq -> yuvinmoq; tara-moq -> taranmoq.",
  },
  {
    order: 51,
    level: "A2",
    title: "Reciprocal & Collaborative Verbs (-ish)",
    titleUzbek: "Birgalik nisbati (-ish)",
    category: "Grammar Essentials",
    description: "Actions done together or mutually with someone.",
    keyVocabulary: [
      { uzbek: "salomlashmoq", english: "to greet one another" },
      { uzbek: "so'zlashmoq", english: "to converse together" },
      { uzbek: "ko'rishmoq", english: "to meet / see each other" },
      { uzbek: "yordamlashmoq", english: "to help each other" },
    ],
    grammarFocus: "Root + -ish: gapirmoq (to speak) -> gaplashmoq (to chat together).",
  },
  {
    order: 52,
    level: "A2",
    title: "Table Manners: Fotiha & Dua",
    titleUzbek: "Dasturxon odoblari va fotiha",
    category: "Culture & Society",
    description: "Opening hands for blessing at the start and end of meals.",
    keyVocabulary: [
      { uzbek: "fotiha tortmoq", english: "to make the concluding meal prayer" },
      { uzbek: "duoga qo'l ochmoq", english: "to open hands in blessing" },
      { uzbek: "Omin!", english: "Amen!" },
      { uzbek: "Dasturxonga baraka bersin!", english: "May God grant abundance to the table!" },
    ],
    grammarFocus: "Hands are brought to the face with 'Omin' to seal the blessing after every shared meal.",
  },
  {
    order: 53,
    level: "A2",
    title: "Complimenting the Host: Qo'lingiz dard ko'rmasin",
    titleUzbek: "Pazandalik va mehmondo'stlikka maqtov",
    category: "Culture & Society",
    description: "Traditional blessings for the cook and host.",
    keyVocabulary: [
      { uzbek: "Qo'lingiz dard ko'rmasin!", english: "May your hands never know pain! (Thank you for cooking)" },
      { uzbek: "Taom juda mazali bo'libdi", english: "The dish turned out very delicious" },
      { uzbek: "osh bo'lsin!", english: "bon appétit / may it nourish you!" },
    ],
    grammarFocus: "'Qo'lingiz dard ko'rmasin' is said to whoever prepared food or handed you tea.",
  },
  {
    order: 54,
    level: "A2",
    title: "Visiting a Friend's Home: Bringing Gifts",
    titleUzbek: "Mehmondorchilik odobi va sovg'a",
    category: "Culture & Society",
    description: "What to bring when visiting someone's house.",
    keyVocabulary: [
      { uzbek: "quruq qo'l bilan bormaslik", english: "not going empty-handed" },
      { uzbek: "shirinlik", english: "sweets / dessert" },
      { uzbek: "tort", english: "cake" },
      { uzbek: "meva-cheva", english: "assorted fresh fruits" },
    ],
    grammarFocus: "It is customary in Uzbek culture never to enter a host's house without bread or sweets.",
  },
  {
    order: 55,
    level: "A2",
    title: "Uzbek Tea Ceremony: Loyta Qilish",
    titleUzbek: "Choy damlash va loyta qilish",
    category: "Culture & Society",
    description: "The ritual of pouring tea three times before serving.",
    keyVocabulary: [
      { uzbek: "choy damlamoq", english: "to brew tea" },
      { uzbek: "loyta qilmoq", english: "to pour tea back into the pot 3 times" },
      { uzbek: "choyni quyib bermoq", english: "to pour and serve tea" },
      { uzbek: "yarim piyola", english: "half-filled bowl (sign of respect)" },
    ],
    grammarFocus: "Serving a half bowl (yarim piyola) means the host wants you to stay and will constantly refill warm tea.",
  },
  {
    order: 56,
    level: "A2",
    title: "Weather Forecasts & Climate",
    titleUzbek: "Ob-havo ma'lumoti va iqlim",
    category: "Nature & Environment",
    description: "Understanding radio and app forecasts (sel, garmsel, qattiq shamol).",
    keyVocabulary: [
      { uzbek: "ob-havo ma'lumoti", english: "weather forecast" },
      { uzbek: "harorat", english: "air temperature" },
      { uzbek: "garmsel", english: "hot dry desert wind" },
      { uzbek: "kuchli shamol", english: "strong wind" },
      { uzbek: "bulutli", english: "cloudy" },
    ],
    grammarFocus: "Garmsel is a unique summer wind blowing from the Kyzylkum desert.",
  },
  {
    order: 57,
    level: "A2",
    title: "Agricultural Seasons & Cotton Harvest",
    titleUzbek: "Qishloq xo'jaligi va paxta mavsumi",
    category: "Nature & Environment",
    description: "Spring sowing, summer irrigation, and autumn harvest.",
    keyVocabulary: [
      { uzbek: "paxta", english: "cotton (white gold)" },
      { uzbek: "hosil terimi", english: "crop harvesting" },
      { uzbek: "dehqon", english: "farmer / cultivator" },
      { uzbek: "ekmoq", english: "to sow / plant" },
      { uzbek: "yetishtirmoq", english: "to grow / harvest" },
    ],
    grammarFocus: "Cotton is poetically referred to as 'oq oltin' (white gold) in Uzbekistan.",
  },
  {
    order: 58,
    level: "A2",
    title: "Shopping for Home Appliances",
    titleUzbek: "Maishiy texnika xarid qilish",
    category: "Everyday Life",
    description: "Buying refrigerators, washing machines, and warranties.",
    keyVocabulary: [
      { uzbek: "muzlatgich / xolodilnik", english: "refrigerator" },
      { uzbek: "kir yuvish mashinasi", english: "washing machine" },
      { uzbek: "kafolat muddati", english: "warranty period" },
      { uzbek: "yetkazib berish", english: "delivery" },
    ],
    grammarFocus: "'Yetkazib bermoq' combines 'yetkazmoq' (to convey) + 'bermoq' (to give/do for someone).",
  },
  {
    order: 59,
    level: "A2",
    title: "Exchanging or Returning Purchased Items",
    titleUzbek: "Xaridni almashtirish va qaytarish",
    category: "Everyday Life",
    description: "Dealing with incorrect sizes, defects, and receipts.",
    keyVocabulary: [
      { uzbek: "almashtirmoq", english: "to exchange / swap" },
      { uzbek: "qaytarib bermoq", english: "to return (an item)" },
      { uzbek: "o'lchami to'g'ri kelmadi", english: "the size did not fit" },
      { uzbek: "nuqsonli / buzuq", english: "defective / faulty" },
    ],
    grammarFocus: "'To'g'ri kelmoq' means 'to fit / match / be appropriate'.",
  },
  {
    order: 60,
    level: "A2",
    title: "Describing Unexpected Problems & Breakdowns",
    titleUzbek: "Kutilmagan muammolar va buzilishlar",
    category: "Everyday Life",
    description: "Things breaking down or getting lost.",
    keyVocabulary: [
      { uzbek: "buzilib qoldi", english: "it broke down suddenly" },
      { uzbek: "yo'qolib qoldi", english: "it got lost" },
      { uzbek: "kechikib qoldim", english: "I ended up being late" },
      { uzbek: "usta chaqirmoq", english: "to call a repair master" },
    ],
    grammarFocus: "Compound verb stem + -ib qolmoq expresses unexpected or unintentional occurrences.",
  },
  {
    order: 61,
    level: "A2",
    title: "Giving Advice with Maslahat",
    titleUzbek: "Maslahat va tavsiya berish",
    category: "Social Life",
    description: "Offering helpful recommendations to peers.",
    keyVocabulary: [
      { uzbek: "maslahat bermoq", english: "to give advice" },
      { uzbek: "tavsiya qilmoq", english: "to recommend" },
      { uzbek: "Mening maslahatim shuki...", english: "My advice is that..." },
      { uzbek: "shunday qilsangiz yaxshi bo'ladi", english: "it would be good if you did this" },
    ],
    grammarFocus: "Conditional -sa + yaxshi bo'ladi: 'Bor-sangiz yaxshi bo'ladi' (It would be good if you went).",
  },
  {
    order: 62,
    level: "A2",
    title: "Expressing Hopes with Umid Qilmoq",
    titleUzbek: "Umid va tilak bildirish",
    category: "Social Life",
    description: "Saying 'I hope that...' and sharing good wishes.",
    keyVocabulary: [
      { uzbek: "umid qilaman", english: "I hope" },
      { uzbek: "ishonaman", english: "I believe / trust" },
      { uzbek: "yaxshi o'tadi deb umid qilaman", english: "I hope it goes well" },
      { uzbek: "Ezgu niyat", english: "pure/good intention" },
    ],
    grammarFocus: "Clause + 'deb umid qilaman' (lit. saying X, I hope).",
  },
  {
    order: 63,
    level: "A2",
    title: "Expressing Preferences with Afzal Ko'rmoq",
    titleUzbek: "Afzal ko'rmoq (Tanlov bildirish)",
    category: "Everyday Life",
    description: "Stating what you prefer over something else.",
    keyVocabulary: [
      { uzbek: "afzal ko'rmoq", english: "to prefer" },
      { uzbek: "choyni qahvadan afzal ko'raman", english: "I prefer tea to coffee" },
      { uzbek: "tanlov", english: "choice / selection" },
    ],
    grammarFocus: "Accusative preferred item + Ablative rejected item + afzal ko'rmoq.",
  },
  {
    order: 64,
    level: "A2",
    title: "Uzbek Wedding Customs: Nikoh To'yi",
    titleUzbek: "Nikoh to'yi an'analari",
    category: "Culture & Society",
    description: "Celebrations, wedding plov (nahorgi osh), and music.",
    keyVocabulary: [
      { uzbek: "nikoh to'yi", english: "wedding ceremony / banquet" },
      { uzbek: "nahorgi osh", english: "early morning wedding plov" },
      { uzbek: "kuyov", english: "groom" },
      { uzbek: "kelin", english: "bride" },
      { uzbek: "to'yxona", english: "wedding banquet palace" },
    ],
    grammarFocus: "Nahorgi osh is served at dawn (around 6:00 AM) exclusively to hundreds of guests.",
  },
  {
    order: 65,
    level: "A2",
    title: "Navruz Spring Festival Traditions",
    titleUzbek: "Navro'z umumxalq bayrami",
    category: "Culture & Society",
    description: "Spring equinox, cooking Sumalak in community cauldrons.",
    keyVocabulary: [
      { uzbek: "Navro'z", english: "Navruz (New Day / Persian New Year)" },
      { uzbek: "sumalak", english: "sprouted wheat sweet pudding" },
      { uzbek: "bahoriy tengkunlik", english: "spring equinox" },
      { uzbek: "sayil", english: "festive outdoor folk gathering" },
    ],
    grammarFocus: "Sumalak is stirred continuously for 24 hours while songs and wishes are shared.",
  },
  {
    order: 66,
    level: "A2",
    title: "Independence Day: Mustaqillik Kuni",
    titleUzbek: "Mustaqillik kuni — 1-sentabr",
    category: "Culture & Society",
    description: "Celebrating Uzbekistan's sovereignty on September 1.",
    keyVocabulary: [
      { uzbek: "Mustaqillik kuni", english: "Independence Day" },
      { uzbek: "istiqlol", english: "independence / freedom" },
      { uzbek: "mushakbozlik", english: "fireworks display" },
      { uzbek: "bayram dasturi", english: "holiday festive program" },
    ],
    grammarFocus: "Uzbekistan declared state independence on September 1, 1991.",
  },
  {
    order: 67,
    level: "A2",
    title: "Teachers' Day: O'qituvchilar Kuni",
    titleUzbek: "O'qituvchi va murabbiylar kuni",
    category: "Culture & Society",
    description: "Honoring teachers and mentors on October 1.",
    keyVocabulary: [
      { uzbek: "murabbiy", english: "mentor / master" },
      { uzbek: "ustoz", english: "esteemed teacher / master" },
      { uzbek: "hurmat ko'rsatmoq", english: "to show deep respect" },
      { uzbek: "guldasta", english: "bouquet of flowers" },
    ],
    grammarFocus: "'Ustoz otangdek ulug'' (A teacher is as honorable as your father) is an Uzbek golden rule.",
  },
  {
    order: 68,
    level: "A2",
    title: "Folk Story Opening: Bir Bor Ekan...",
    titleUzbek: "Ertak tili: Bir bor ekan, bir yo'q ekan",
    category: "Culture & Arts",
    description: "Understanding traditional Uzbek fairy tale formulas.",
    keyVocabulary: [
      { uzbek: "Bir bor ekan, bir yo'q ekan", english: "Once upon a time (lit. one was, one was not)" },
      { uzbek: "qadim zamonda", english: "in ancient times" },
      { uzbek: "ertak", english: "fairy tale / folk tale" },
      { uzbek: "podsho / xon", english: "king / khan" },
    ],
    grammarFocus: "Traditional Uzbek storytelling uses the narrative suffix -gan ekan / -ibdi.",
  },
  {
    order: 69,
    level: "A2",
    title: "Describing a Memorable Journey",
    titleUzbek: "Unutilmas sayohat haqida hikoya",
    category: "Travel & Places",
    description: "Narrating a travel experience in the past tense.",
    keyVocabulary: [
      { uzbek: "unutilmas", english: "unforgettable" },
      { uzbek: "taassurot", english: "impression" },
      { uzbek: "sayohat qilmoq", english: "to travel" },
      { uzbek: "mening xotiramda qoldi", english: "it stayed in my memory" },
    ],
    grammarFocus: "Combining definite past (-di) and indefinite past (-gan) to build a rich story.",
  },
  {
    order: 70,
    level: "A2",
    title: "Polite Disagreement & Counterarguments",
    titleUzbek: "Xushmuomalalik bilan e'tiroz bildirish",
    category: "Communication",
    description: "Voicing differing opinions diplomatically.",
    keyVocabulary: [
      { uzbek: "Fikringizga qo'shilaman, lekin...", english: "I agree with your thought, but..." },
      { uzbek: "Boshqa tomondan qarasak...", english: "If we look from the other side..." },
      { uzbek: "har kimning o'z fikri bor", english: "everyone has their own opinion" },
    ],
    grammarFocus: "'Qarasak' is the conditional 1st person plural ('if we look').",
  },
  {
    order: 71,
    level: "A2",
    title: "Giving Precise Street Directions",
    titleUzbek: "Aniq ko'cha yo'nalishlarini berish",
    category: "Travel & Places",
    description: "Navigating roundabouts, traffic lights, and landmarks.",
    keyVocabulary: [
      { uzbek: "chorraha", english: "crossroad / intersection" },
      { uzbek: "svetofor", english: "traffic light" },
      { uzbek: "aylanma yo'l", english: "traffic circle / roundabout" },
      { uzbek: "mo'ljal", english: "landmark / reference point" },
    ],
    grammarFocus: "'Mo'ljal nima?' (What is the nearby landmark?) is asked by all delivery drivers.",
  },
  {
    order: 72,
    level: "A2",
    title: "Describing Symptoms: Flu & Cold",
    titleUzbek: "Gripp va shamollash belgilari",
    category: "Health & Well-being",
    description: "Detailed medical conversation for common ailments.",
    keyVocabulary: [
      { uzbek: "gripp", english: "flu / influenza" },
      { uzbek: "burun bitishi", english: "stuffy nose" },
      { uzbek: "holsizlik", english: "weakness / fatigue" },
      { uzbek: "issiqlik tushiruvchi", english: "fever reducer" },
    ],
    grammarFocus: "Suffix -lik creates abstract nouns: hol (strength/condition) + siz + lik = weakness.",
  },
  {
    order: 73,
    level: "A2",
    title: "Visiting the Dentist",
    titleUzbek: "Tish shifokorida",
    category: "Health & Well-being",
    description: "Toothache, fillings, and dental hygiene.",
    keyVocabulary: [
      { uzbek: "tish shifokori / stomatolog", english: "dentist" },
      { uzbek: "tish og'rig'i", english: "toothache" },
      { uzbek: "plomba qo'ymoq", english: "to put in a dental filling" },
      { uzbek: "og'riqsizlantirish", english: "anesthesia / numbing" },
    ],
    grammarFocus: "Possessive alternation: og'riq + i -> og'rig'i (q softens to g').",
  },
  {
    order: 74,
    level: "A2",
    title: "Ordering at a Fast Food / Cafe",
    titleUzbek: "Tezkor ovqatlanish shahobchasida",
    category: "Food & Dining",
    description: "Lavash, burger, doner kebab, and takeaway orders.",
    keyVocabulary: [
      { uzbek: "lavash", english: "shawarma wrap in thin flatbread" },
      { uzbek: "olib ketishga", english: "for takeaway / to go" },
      { uzbek: "shu yerda yeyishga", english: "for dining in here" },
      { uzbek: "kartoshka fri", english: "french fries" },
    ],
    grammarFocus: "Tashkent lavash is a renowned Uzbek fast food staple with meat, cheese, and tomato.",
  },
  {
    order: 75,
    level: "A2",
    title: "Talking About Hobbies: Photography & Art",
    titleUzbek: "Qiziqishlar: Fotosurat va rasm chizish",
    category: "Sports & Hobbies",
    description: "Taking photos and creative drawing.",
    keyVocabulary: [
      { uzbek: "suratga olmoq", english: "to take a photo" },
      { uzbek: "rasm chizmoq", english: "to draw / paint a picture" },
      { uzbek: "fotoapparat", english: "camera" },
      { uzbek: "ko'rgazma", english: "exhibition / art gallery" },
    ],
    grammarFocus: "'Suratga olmoq' requires dative on subject photographed if specified.",
  },
  {
    order: 76,
    level: "A2",
    title: "Talking About Hobbies: Gardening",
    titleUzbek: "Bog'dorchilik va gul o'stirish",
    category: "Sports & Hobbies",
    description: "Planting flowers, watering trees, and harvesting homegrown fruit.",
    keyVocabulary: [
      { uzbek: "bog'dorchilik", english: "gardening / horticulture" },
      { uzbek: "gul o'stirmoq", english: "to grow flowers" },
      { uzbek: "suv quymoq", english: "to water plants" },
      { uzbek: "ko'chat", english: "seedling / sapling" },
    ],
    grammarFocus: "Compound 'suv quymoq' means 'to pour water / irrigate'.",
  },
  {
    order: 77,
    level: "A2",
    title: "Describing Childhood Memories",
    titleUzbek: "Bolalik xotiralari",
    category: "Communication",
    description: "Talking about games, school days, and growing up.",
    keyVocabulary: [
      { uzbek: "bolaligimda", english: "in my childhood" },
      { uzbek: "maktab davri", english: "school days / era" },
      { uzbek: "o'rtoqlarim bilan", english: "with my close childhood friends" },
      { uzbek: "eslayman", english: "I remember" },
    ],
    grammarFocus: "Temporal noun + locative: 'bolalik-im-da' = in my childhood.",
  },
  {
    order: 78,
    level: "A2",
    title: "Explaining Job Responsibilities",
    titleUzbek: "Ishdagi vazifalar va majburiyatlar",
    category: "Work & Study",
    description: "Describing what you do at the office or company.",
    keyVocabulary: [
      { uzbek: "vazifa", english: "duty / task" },
      { uzbek: "javobgarman", english: "I am responsible for" },
      { uzbek: "loyiha", english: "project" },
      { uzbek: "jamoa", english: "team" },
      { uzbek: "hisobot tayyorlamoq", english: "to prepare a report" },
    ],
    grammarFocus: "Dative + javobgar: 'Loyiha-ga javobgarman' (I am responsible for the project).",
  },
  {
    order: 79,
    level: "A2",
    title: "University Life & Exams",
    titleUzbek: "Universitet hayoti va imtihonlar",
    category: "Work & Study",
    description: "Lectures, seminars, preparing for finals, and grades.",
    keyVocabulary: [
      { uzbek: "ma'ruza", english: "lecture" },
      { uzbek: "imtihon topshirmoq", english: "to take/pass an exam" },
      { uzbek: "baho / ball", english: "grade / mark" },
      { uzbek: "kursdosh", english: "university classmate" },
      { uzbek: "stipendiya", english: "scholarship / student stipend" },
    ],
    grammarFocus: "Suffix -dosh denotes peer of same status: kursdosh (course-mate), vatandosh (compatriot).",
  },
  {
    order: 80,
    level: "A2",
    title: "Writing a Short Note or Message",
    titleUzbek: "Qisqa xat yoki xabar yozish",
    category: "Communication",
    description: "Drafting SMS, Telegram notes, and reminders.",
    keyVocabulary: [
      { uzbek: "xabar yozmoq", english: "to write a message" },
      { uzbek: "eslatma", english: "reminder / memo" },
      { uzbek: "javob kutaman", english: "I await your reply" },
      { uzbek: "Hurmat bilan", english: "With respect (formal closing)" },
    ],
    grammarFocus: "Telegram is the primary communication and business channel in Uzbekistan.",
  },
  {
    order: 81,
    level: "A2",
    title: "Shopping for Shoes and Sizing",
    titleUzbek: "Poyabzal tanlash va o'lchami",
    category: "Everyday Life",
    description: "Trying on shoes, checking sizes, and shoe materials.",
    keyVocabulary: [
      { uzbek: "o'lchab ko'rmoq", english: "to try on (clothing/shoes)" },
      { uzbek: "tor", english: "tight / narrow" },
      { uzbek: "keng", english: "wide / loose" },
      { uzbek: "charm / teri", english: "genuine leather" },
    ],
    grammarFocus: "Compound verb stem + -ib ko'rmoq means 'to try doing something' (kiyib ko'rmoq).",
  },
  {
    order: 82,
    level: "A2",
    title: "Asking About Opening Hours",
    titleUzbek: "Ish vaqti haqida so'rash",
    category: "Everyday Life",
    description: "Inquiring about shop and museum opening/closing times.",
    keyVocabulary: [
      { uzbek: "ish vaqti", english: "working hours" },
      { uzbek: "ochilish vaqti", english: "opening time" },
      { uzbek: "yopilish vaqti", english: "closing time" },
      { uzbek: "tushlik tanaffusi", english: "lunch break" },
    ],
    grammarFocus: "'Dam olish kunlarisiz' means 'without days off / open 7 days a week'.",
  },
  {
    order: 83,
    level: "A2",
    title: "Reporting Lost Belongings",
    titleUzbek: "Yo'qolgan buyumlar haqida xabar berish",
    category: "Travel & Places",
    description: "Reporting a lost wallet, phone, or passport to staff.",
    keyVocabulary: [
      { uzbek: "yo'qotib qo'ymoq", english: "to lose something" },
      { uzbek: "topib olmoq", english: "to find" },
      { uzbek: "hujjatlarim", english: "my documents / ID" },
      { uzbek: "topilmalar byurosi", english: "lost and found office" },
    ],
    grammarFocus: "'Qo'ymoq' as auxiliary indicates finalized, unfortunate completion.",
  },
  {
    order: 84,
    level: "A2",
    title: "Describing Climate Zones of Uzbekistan",
    titleUzbek: "O'zbekistonning tabiiy zonalari",
    category: "Nature & Environment",
    description: "Steppes, Kyzylkum desert, Tian Shan mountains, and fertile valleys.",
    keyVocabulary: [
      { uzbek: "cho'l", english: "desert" },
      { uzbek: "voha", english: "oasis" },
      { uzbek: "vodiy", english: "valley (e.g. Fergana Valley)" },
      { uzbek: "daryo", english: "river (Amudarya, Syrdarya)" },
    ],
    grammarFocus: "Fergana Valley ('Farg'ona vodiysi') is known as the pearl of Central Asia.",
  },
  {
    order: 85,
    level: "A2",
    title: "Expressing Certainty: Aniq & Shubhasiz",
    titleUzbek: "Ishonch bildirish: Aniq, Shubhasiz",
    category: "Communication",
    description: "Stating confidence in facts or outcomes.",
    keyVocabulary: [
      { uzbek: "aniq", english: "clear / exact / definite" },
      { uzbek: "shubhasiz", english: "without doubt / undoubtedly" },
      { uzbek: "ishonchim komil", english: "I am confident / certain" },
    ],
    grammarFocus: "Privative suffix -siz denotes 'without': shubha (doubt) + siz = without doubt.",
  },
  {
    order: 86,
    level: "A2",
    title: "Expressing Uncertainty: Balki & Ehtimol",
    titleUzbek: "Noaniqlik bildirish: Balki, Ehtimol",
    category: "Communication",
    description: "Saying 'maybe', 'perhaps', and 'probably'.",
    keyVocabulary: [
      { uzbek: "balki", english: "maybe / perhaps" },
      { uzbek: "ehtimol", english: "probably / likely" },
      { uzbek: "bo'lishi mumkin", english: "it is possible / could be" },
    ],
    grammarFocus: "Both balki and ehtimol usually head the sentence.",
  },
  {
    order: 87,
    level: "A2",
    title: "Booking Hotel Rooms",
    titleUzbek: "Mehmonxonada xona band qilish",
    category: "Travel & Places",
    description: "Single room, double room, breakfast included, check-out time.",
    keyVocabulary: [
      { uzbek: "mehmonxona", english: "hotel" },
      { uzbek: "xona band qilmoq", english: "to book/reserve a room" },
      { uzbek: "bir kishilik xona", english: "single room" },
      { uzbek: "nonushta kiritilgan", english: "breakfast included" },
    ],
    grammarFocus: "'Band qilmoq' means 'to reserve / occupy'.",
  },
  {
    order: 88,
    level: "A2",
    title: "Hotel Check-in & Inquiries",
    titleUzbek: "Mehmonxonaga joylashish",
    category: "Travel & Places",
    description: "Wi-Fi password, air conditioner remote, and luggage storage.",
    keyVocabulary: [
      { uzbek: "ro'yxatga olish stoli", english: "reception desk" },
      { uzbek: "Wi-Fi paroli", english: "Wi-Fi password" },
      { uzbek: "konditsioner", english: "air conditioner" },
      { uzbek: "masofadan boshqarish pulti", english: "remote control" },
    ],
    grammarFocus: "Izafet: Wi-Fi + parol + i = Wi-Fi paroli.",
  },
  {
    order: 89,
    level: "A2",
    title: "Describing a Daily Routine in Detail",
    titleUzbek: "Kun tartibini batafsil so'zlash",
    category: "Everyday Life",
    description: "Sequencing an entire workday from morning till night with connectors.",
    keyVocabulary: [
      { uzbek: "avvalambor", english: "first of all" },
      { uzbek: "so'ngra / keyin", english: "then / afterwards" },
      { uzbek: "nihoyat", english: "finally / at last" },
      { uzbek: "odatda", english: "usually / typically" },
    ],
    grammarFocus: "Use cohesive sequence markers: Avval... keyin... undan so'ng... nihoyat...",
  },
  {
    order: 90,
    level: "A2",
    title: "Ordering Hot Uzbek Soups",
    titleUzbek: "Milliy sho'rvalar buyurtma qilish",
    category: "Food & Dining",
    description: "Sho'rva, Mastava (rice soup), and Chuchvara (dumpling soup).",
    keyVocabulary: [
      { uzbek: "sho'rva", english: "lamb broth soup with vegetables" },
      { uzbek: "mastava", english: "savory meat, rice, and vegetable soup" },
      { uzbek: "chuchvara", english: "mini dumplings in clear broth" },
      { uzbek: "qatiq", english: "sour milk / yogurt" },
    ],
    grammarFocus: "Mastava is warmly known as 'suyuq osh' (liquid plov) due to its shared ingredients.",
  },
  {
    order: 91,
    level: "A2",
    title: "Tasting Uzbek Sweets & Halva",
    titleUzbek: "O'zbek shirinliklari va holva",
    category: "Food & Dining",
    description: "Samarkand halva, novvot rock sugar, and parvarda candies.",
    keyVocabulary: [
      { uzbek: "holva", english: "halva" },
      { uzbek: "novvot", english: "crystal grape rock candy" },
      { uzbek: "parvarda", english: "traditional powdery sugar candy" },
      { uzbek: "mayiz", english: "raisins" },
      { uzbek: "bodom", english: "almonds" },
    ],
    grammarFocus: "Novvot is traditionally dissolved into hot green tea for sore throats.",
  },
  {
    order: 92,
    level: "A2",
    title: "Asking Someone's Profession & Background",
    titleUzbek: "Kasb va soha haqida suhbat",
    category: "Work & Study",
    description: "Inquiring about someone's career trajectory.",
    keyVocabulary: [
      { uzbek: "Qaysi sohada ishlaysiz?", english: "In which field do you work?" },
      { uzbek: "mutaxassis", english: "specialist / professional" },
      { uzbek: "tajriba", english: "experience" },
      { uzbek: "IT sohasi", english: "IT / Tech sector" },
    ],
    grammarFocus: "Suffix -da on 'soha': 'qaysi sohada' (in which sphere/field).",
  },
  {
    order: 93,
    level: "A2",
    title: "Describing Daily Work with Computers",
    titleUzbek: "Kompyuterda ishlash",
    category: "Work & Study",
    description: "Writing code, emails, video calls, and spreadsheets.",
    keyVocabulary: [
      { uzbek: "elektron pochta", english: "email" },
      { uzbek: "onlayn uchrashuv", english: "online meeting" },
      { uzbek: "fayl yuklamoq", english: "to download / upload a file" },
      { uzbek: "dasturlash", english: "programming / coding" },
    ],
    grammarFocus: "'Yuklamoq' means both to load/upload and to download based on context (ko'chirib olmoq = download).",
  },
  {
    order: 94,
    level: "A2",
    title: "Asking for and Giving Phone Numbers",
    titleUzbek: "Telefon raqamini so'rash va yozib olish",
    category: "Communication",
    description: "Reciting phone numbers in Uzbek digit pairs.",
    keyVocabulary: [
      { uzbek: "Telefon raqamingiz necha?", english: "What is your phone number?" },
      { uzbek: "raqam", english: "number / digit" },
      { uzbek: "kod", english: "area / country code" },
      { uzbek: "qo'ng'iroq qilmoq", english: "to give a call" },
    ],
    grammarFocus: "Uzbek phone numbers are typically grouped by tens: masalan, 90 123 45 67.",
  },
  {
    order: 95,
    level: "A2",
    title: "Describing Weekend Sports and Leisure",
    titleUzbek: "Hafta oxiri sport va hordiq",
    category: "Sports & Hobbies",
    description: "Bicycle rides, swimming in Charvak reservoir, and mountain hikes.",
    keyVocabulary: [
      { uzbek: "velosiped haydamoq", english: "to ride a bicycle" },
      { uzbek: "suzmoq", english: "to swim" },
      { uzbek: "Chorvoq suv ombori", english: "Charvak water reservoir" },
      { uzbek: "cho'milmoq", english: "to bathe / swim recreationally" },
    ],
    grammarFocus: "'Suzmoq' refers to the stroke/skill of swimming; 'cho'milmoq' means recreational bathing.",
  },
  {
    order: 96,
    level: "A2",
    title: "Expressing Congratulations on Success",
    titleUzbek: "Muvaffaqiyat bilan tabriklash",
    category: "Social Life",
    description: "Congratulating friends on new jobs, graduation, or buying a home.",
    keyVocabulary: [
      { uzbek: "Yangi uyingiz qutlug' bo'lsin!", english: "Congratulations on your new home!" },
      { uzbek: "Muvaffaqiyat muborak!", english: "Blessed success!" },
      { uzbek: "Qadamingiz qutlug' bo'lsin!", english: "May your new step/arrival be blessed!" },
    ],
    grammarFocus: "'Qutlug' bo'lsin' is the auspicious formula for new beginnings.",
  },
  {
    order: 97,
    level: "A2",
    title: "Expressing Condolences & Sympathy",
    titleUzbek: "Hamdardlik va ta'ziya bildirish",
    category: "Social Life",
    description: "Offering respectful condolences to mourning families.",
    keyVocabulary: [
      { uzbek: "Bandalikni bajo keltiribdilar", english: "They have passed away (formal pious expression)" },
      { uzbek: "Joyi jannatda bo'lsin", english: "May their place be in Paradise" },
      { uzbek: "Sabr tilayman", english: "I wish you patience and strength" },
      { uzbek: "hamdardlik", english: "sympathy / condolence" },
    ],
    grammarFocus: "Expressing 'Sabr tilayman' offers spiritual composure and deep compassion.",
  },
  {
    order: 98,
    level: "A2",
    title: "Making Long-Term Plans for Next Year",
    titleUzbek: "Kelgusi yil uchun rejalar",
    category: "Grammar Essentials",
    description: "Discussing goals with -moqchiman and kelasi yili.",
    keyVocabulary: [
      { uzbek: "kelasi yili", english: "next year" },
      { uzbek: "maqsad qo'ymoq", english: "to set a goal" },
      { uzbek: "chet elga bormoqchiman", english: "I intend to go abroad" },
      { uzbek: "yangi til o'rganmoqchiman", english: "I intend to learn a new language" },
    ],
    grammarFocus: "'Kelasi' (coming) modifies temporal nouns: kelasi hafta, kelasi oy, kelasi yil.",
  },
  {
    order: 99,
    level: "A2",
    title: "Common Uzbek Proverbs in Daily Talk",
    titleUzbek: "Kundalik maqollar",
    category: "Culture & Arts",
    description: "Five famous proverbs used in everyday Uzbek conversations.",
    keyVocabulary: [
      { uzbek: "Mehnat, mehnatning tagi — rohat", english: "Hard work yields sweet relaxation" },
      { uzbek: "Yaxshi so'z — jonga oziq", english: "A kind word nourishes the soul" },
      { uzbek: "Sabr tagi — sariq oltin", english: "Patience leads to yellow gold" },
      { uzbek: "maqol", english: "proverb" },
    ],
    grammarFocus: "Proverbs distill Uzbek cultural philosophy and values.",
  },
  {
    order: 100,
    level: "A2",
    title: "A2 Capstone: Social Independence in Uzbekistan",
    titleUzbek: "A2 Xulosa: Mustaqil ijtimoiy muloqot",
    category: "Communication",
    description: "Synthesizing past, present continuous, and future tenses in an unscripted cultural conversation.",
    keyVocabulary: [
      { uzbek: "mustaqil muloqot", english: "independent conversation" },
      { uzbek: "fikr almashish", english: "exchange of views" },
      { uzbek: "erkin gapirmoq", english: "to speak freely" },
      { uzbek: "til bilish darajasi", english: "language proficiency level" },
    ],
    grammarFocus: "Demonstrates mastery of A2 tenses (-di, -gan, -yapti, -moqchi) and courteous social registers.",
  },
  {
    order: 101, level: "A2", title: "A2 Review: Tense Choices", titleUzbek: "A2 takrorlash: Zamon tanlash", category: "Review", description: "Choose past, present continuous, and intention forms in context.", keyVocabulary: [{ uzbek: "zamon", english: "tense" }, { uzbek: "kecha", english: "yesterday" }, { uzbek: "hozir", english: "now" }, { uzbek: "ertaga", english: "tomorrow" }], grammarFocus: "Contrast -di, -yapti, and -moqchi across a timeline.",
  },
  {
    order: 102, level: "A2", title: "A2 Review: Health & Services", titleUzbek: "A2 takrorlash: Sog'liq va xizmatlar", category: "Review", description: "Explain a practical problem and ask a service provider for help.", keyVocabulary: [{ uzbek: "shifokor", english: "doctor" }, { uzbek: "muammo", english: "problem" }, { uzbek: "yordam", english: "help" }, { uzbek: "uchrashuv", english: "appointment" }], grammarFocus: "Use polite questions, past descriptions, and advice forms.",
  },
  {
    order: 103, level: "A2", title: "A2 Review: Social Plans", titleUzbek: "A2 takrorlash: Ijtimoiy rejalar", category: "Review", description: "Invite, accept, decline, and rearrange plans with friends.", keyVocabulary: [{ uzbek: "taklif", english: "invitation" }, { uzbek: "bo'sh", english: "free" }, { uzbek: "uchrashmoq", english: "to meet" }, { uzbek: "keyinroq", english: "later" }], grammarFocus: "Use future intentions and polite response formulas.",
  },
  {
    order: 104, level: "A2", title: "A2 Review: Culture & Travel", titleUzbek: "A2 takrorlash: Madaniyat va sayohat", category: "Review", description: "Share a past travel experience and a future recommendation.", keyVocabulary: [{ uzbek: "sayohat", english: "trip" }, { uzbek: "mehmonxona", english: "hotel" }, { uzbek: "tavsiya", english: "recommendation" }, { uzbek: "tajriba", english: "experience" }], grammarFocus: "Link past experience with comparative recommendations.",
  },
  {
    order: 105, level: "A2", title: "A2 Final Can-Do Check", titleUzbek: "A2 yakuniy ko'nikmalar tekshiruvi", category: "Capstone", description: "Demonstrate independent communication across routine social and practical situations.", keyVocabulary: [{ uzbek: "ishonch", english: "confidence" }, { uzbek: "mustaqil", english: "independent" }, { uzbek: "muvaffaqiyat", english: "success" }, { uzbek: "keyingi bosqich", english: "next stage" }], grammarFocus: "Integrate A2 tenses, comparisons, and respectful interaction.",
  },
];
